const url='https://neomobilestoragenew.blob.core.windows.net';
const Images = {
  accounts: {uri:url +'/neomobile/Images/accounts.png'},
  allac:{uri:url +'/neomobile/Images/allac.png'},
  crypto:{uri:url +'/neomobile/Images/crypto.png'},
  cards:{uri:url +'/neomobile/Images/cards.png'},
  arrowright:{uri:url +'/neomobile/Images/arrow-right.png'},
  circlecheck:{uri:url +'/neomobile/Images/circle-check.png'},
  close:{uri:url +'/neomobile/Images/close.png'},
  createaccount:{uri:url +'/neomobile/Images/create-account.png'},
  errorclose:{uri:url +'/neomobile/Images/errorclose.png'},
  accounts_f:{
    info:{uri:url +'/neomobile/Images/accounts/info.png'}
  },
  avatar: {
    avatar: {uri:url +'/neomobile/Images/avatar/img_avatar.png'},
    avatar01: {uri:url +'/neomobile/Images/avatar/img_avatar_01.png'},
    avatar02: {uri:url +'/neomobile/Images/avatar/img_avatar_02.png'},
    avatar03: {uri:url +'/neomobile/Images/avatar/img_avatar_03.png'},
    avatar04: {uri:url +'/neomobile/Images/avatar/img_avatar_04.png'},
    avatar05: {uri:url +'/neomobile/Images/avatar/img_avatar_05.png'},
    avatar06: {uri:url +'/neomobile/Images/avatar/img_avatar_06.png'},
    avatar07: {uri:url +'/neomobile/Images/avatar/img_avatar_07.png'},
    avatar08: {uri:url +'/neomobile/Images/avatar/img_avatar_08.png'},
    avatar09: {uri:url +'/neomobile/Images/avatar/img_avatar_09.png'},
    avatar10: {uri:url +'/neomobile/Images/avatar/img_avatar_10.png'},
  },
  crypto_f:{
    crypto_f:{uri:url +'/neomobile/Images/crypto/arrow-down.png'},
    crypto_f1:{uri:url +'/neomobile/Images/crypto/buy-icon.png'},
    crypto_f2:{uri:url +'/neomobile/Images/crypto/buy.png'},
    crypto_f3:{uri:url +'/neomobile/Images/crypto/close-sheet.png'},
    crypto_f4:{uri:url +'/neomobile/Images/crypto/cost-icon.png'},
    crypto_f5:{uri:url +'/neomobile/Images/crypto/crypto-graph.png'},
    crypto_f6:{uri:url +'/neomobile/Images/crypto/deposit-required.png'},
    crypto_f7:{uri:url +'/neomobile/Images/crypto/instantSgd.png'},
    crypto_f8:{uri:url +'/neomobile/Images/crypto/receive.png'},
    crypto_f9:{uri:url +'/neomobile/Images/crypto/sell-flip.png'},
    crypto_f10:{uri:url +'/neomobile/Images/crypto/sell-icon.png'},
    crypto_f11:{uri:url +'/neomobile/Images/crypto/sell.png'},
    crypto_f12:{uri:url +'/neomobile/Images/crypto/send.png'},
    crypto_f13:{uri:url +'/neomobile/Images/crypto/status-graph.png'},
  },
  coins:{
    coinbtc:{uri:url +'/neomobile/Images/coins/btc.png'},
    coineth:{uri:url +'/neomobile/Images/coins/eth.png'},
    coineusdc:{uri:url +'/neomobile/Images/coins/usdc.png'},
    coineusdt:{uri:url +'/neomobile/Images/coins/usdt.png'},

  },
  cards_f:{
    cards_f1:{uri:url +'/neomobile/Images/cards/arrowright.png'},
    cards_f2:{uri:url +'/neomobile/Images/cards/bags.png'},
    cards_f3:{uri:url +'/neomobile/Images/cards/sell.png'},
    cards_f4:{uri:url +'/neomobile/Images/cards/buy.png'},
    cards_f5:{uri:url +'/neomobile/Images/cards/card2.png'},
    cards_f6:{uri:url +'/neomobile/Images/cards/close.png'},
    cards_f7:{uri:url +'/neomobile/Images/cards/deposite.png'},
    cards_f8:{uri:url +'/neomobile/Images/cards/freeze.png'},
    cards_f9:{uri:url +'/neomobile/Images/cards/getpin.png'},
    cards_f10:{uri:url +'/neomobile/Images/cards/more.png'},
    cards_f11:{uri:url +'/neomobile/Images/cards/reissue.png'},
    cards_f12:{uri:url +'/neomobile/Images/cards/robot.png'},
    cards_f13:{uri:url +'/neomobile/Images/cards/terminate.png'},
    cards_f14:{uri:url +'/neomobile/Images/cards/topup.png'},
    cards_f15:{uri:url +'/neomobile/Images/cards/transfer.png'},
    cards_f16:{uri:url +'/neomobile/Images/cards/unfreeze.png'},
    cards_f17:{uri:url +'/neomobile/Images/cards/view.png'},
    cards_f18:{uri:url +'/neomobile/Images/cards/visa.png'},
    cards_f19:{uri:url +'/neomobile/Images/cards/withdraw.png'},
    
  }
};
export default Images;
