export const ADDRESSBOOK_CONSTANTS = {
  FIAT_WALLETS: (customerId: any) => `api/v1/ExchangeWallet/Exchange/FiatWallets/${customerId}`,
  PAYEES_FIAT: (customerId: any, page: any, pageSize: any) => `api/v1/Common/payees/${customerId}/fiat/${pageSize}/${page}/all`,
  PAYEES_CRYPTO: (page: any, pageSize: any, currecy: any) => `api/v1/payees/wallets/crypto?page=${page}&pageSize=${pageSize}&currency=${currecy}`,
  PAYEES_FIAT_WALLETS: (page: any, pageSize: any, currecy: any) => `api/v1/payees/wallets/fiat?page=${page}&pageSize=${pageSize}&currency=${currecy}`,
  PAYEES_STATUS: (id: any, statusType: any) => `api/v1/payees/${id}/${statusType}`,
  PAYEE_FIAT_DETAILS: (id: any) => `/api/v1/Common/Payee/fiat/${id}`,
  PAYEES_CRYPTO_DETAILS: (id: any) => `/api/v1/payees/crypto/${id}`,
  PAYEES_FIAT_ID: (id: any) => `/api/v1/Payees/fiat/${id}`,
  PAYEES_FIAT_VIEW: (id: any) => `/api/v1/Payees/fiat/${id}/view`,
  BANK_ACCOUNTS: (id: any, appName: any) => `/api/v1/ExchangeWallet/bank/accountslu/${id}/${appName}`,
  EXCHANGE_FIAT_WALLETS: (id: any, appName: any) => `/api/v1/ExchangeWallet/Exchange/FiatWallets/${id}/${appName}`,
  FIAT_CURRENCY_LU: `/api/v1/Common/FiatCurrencyLu`,
  BANKS_LU: `/api/v1/Affiliate/m/bankslu`,
  PAYEE_STATUS_INFO: (payeeId: any) => `/api/v1/payeestatusinfo/${payeeId}`,
  SATHOSI_TEST: (network: any, address: any) => `api/v1/payees/deposit/sathositest/${network}/${address}`,
  SATHOSI_TEST_POST: `api/v1/payees/deposit/sathositest`,
  WALLETS: (crypto: any) => `api/v1/Wallets/${crypto}`,
  PAYEE_LU: (customerId: any, coin: any) => `api/v1/ExchangeWallet/Exchange/PayeeLu/${customerId}/${coin}`,
  CRYPTO_CONFIRM: 'api/v1/ExchangeWallet/Crypto/Confirm',
  PAYEES_CRYPTO_POST: 'api/v1/payees/crypto',
  PAYEES_CRYPTO_PUT: '/api/v1/payees/crypto',
  NETWORK_LU: (walletcode: any, customerId: any) => `api/v1/Common/Wallets/NetWorkLU/${walletcode}/${customerId}`,
  CRYPTO_WALLETS: (customerId: any) => `api/v1/ExchangeWallet/Exchange/CryptoWallets/${customerId}`,
  WITHDRAW_CRYPTO: 'api/v1/ExchangeTransaction/Withdraw/Crypto',
  VERIFY_WALLET_ADDRESS: `/api/v1/Common/M/verifywalletaddress`,
  MERCHANT_WALLETS: (customerId: any, actiontype: any) => `api/v1/Merchant/Wallets/${customerId}/${actiontype}`,
  WALLET_SOURCES_FIRST_PARTY: `api/v1/Common/WalletSources/FirstParty-WalletSource`,
  WALLET_SOURCES_THIRD_PARTY: `api/v1/Common/WalletSources/ThirdParty-WalletSource`,
  API_V1_PAYEES_RECIPIENT_PAYEE_CRYPTO: "api/v1/payees/recipient/PayeeCrypto",
  CUSTOMERS_PROFILE_PERSONAL: '/api/v1/customers/profile/personal',
  CUSTOMERS_PROFIL_BUSINESS: '/api/v1/customers/profile/business',
  PERSONAL: "personal",
  BUSINESS: "business",
  PAYEES_LOOKUP: 'api/v1/payees/lookup',
  PAYMENT_TYPES: '/api/v1/paymenttypes',
  BRANCHES: '/api/v1/payees/branches',
  IBAN_VALIDATE: 'api/v1/iban',
  CURRENCY_COUNTRIES: 'api/v1/payee/currencywithcountries',
  PROVIDER_BANKS: 'api/v1/payees/providerbanks',
  DYNAMIC_LOOKUP: '/api/v1',
  RECIPIENT_FIAT: 'api/v1/payees/recipient/PayeeFiat',
  RECIPIENT_CRYPTO: 'api/v1/payees/recipient/PayeeCrypto',
  UPDATE_PAYMENT_FIAT: 'api/v1/payees/fiat',
  SAVE_PAYMENT_FIAT: 'api/v1/Payees/Fiat'
};
