
export const ADD_BOOK_CONST = {
    NEW: "New",
    WHITELIST_NAME: "Favorite Name",
    CURRENCY: "Currency",
    IBAN: "IBAN / Account Number",
    WHITELISTING_STATUS: "Whitelisting Status",
    LOAD_MORE: "Load More",
    CRYPTO_VIEW: "Crypto View",
    PERSONAL_DETAILS: "Recipient's Details",
    BANK_DETAILS: "Bank Details",
    RECIPIENTS_ADDRESS: "Recipient's Address",
    BENEFICIARY_NAME: "Beneficiary Name",
    COUNTRY: "Country",
    STATE: "State",
    CITY: "City",
    CONFIRM_ACTIVE_INACTIVE: "Confirm Active/InActive",
    FIAT_VIEW: "Fiat View",
    SELECT_ASSET: "Select Asset",
    TOKEN: "Token :",
    REASON_FOR_REJECTION: "Reason for rejection",
    FAVORITE_NAME: "Favorite Name",
    ACCOUNT_TYPE: "Account Type ",
    BANK_NAME: "Bank Name",
    TRANSFER_TYPE: "Transfer Type",
    SWIFT_BIC_CODE: "Swift / BIC Code",
    ADD_CRYPTO_PAYEE: "addCryptoPayee",
    ADD_CONTACT_COMPONENT:"AddContact",
    SEARCH_COIN:'Search Coin',
    FIRAT_NAME:"First Name",
    LAST_NAME:"Last Name",
    MIDLE_NAME:"Middle Name",
    BOD:"Birth Date",
    EMAI:"Email",
    PHONE:"Phone",
    ADDRESS_DETAILS_TITLE:"Address Details",
    ADDRESS:"Address",
    PIN_CODE:"Pin Code",
    PAYMENT_DETAILS:"Payment Details",
    ADDITIONAL_DETAILS_TITLE:"Additional Details",
    ADD_PAYEE:"Add Payee",
    ADD_RECIPIENT_COMPONENT:"AddRecipient",
    PAYMENT:"Payments",
    SEARCH_PAYEE:"Search Payee",
    SEARCH:"search",
    ANTD_SEARCH_ICON:"search1",
    SELECT_MODULE:'Select Module',
    FILTER_ICON:"filter",
    SLIDE:"slide",
    BUSINES_FIAT_PAYEE:"BusinessFiatPayee",
    PAYMENT_TYPE: "paymentType",
    PAYEES:'payees',
    ADDRESS_BOOK:'addressbook',
    CRYPTO_ACTION:'crypto',
    FIAT_ACTION:'fiat',

    APP_NAMES:{
        EXCHANGE_PAY:"Exchange",
        BANK:"Bank",
        PAYMENTS:"Payments",
        ALL:"All",
    },
}
export interface Loaders {
    btnDisabled: boolean,
    summryLoading: boolean,
    module: boolean
};