export const PAYOUT_CONSTANTS = {
  ID: "id",
  NAME:"name",
  NUMARIC: "numeric",
  CONFIRM: "Confirm",
  CANCEL: "Cancel",
  NO_DATA_AVAILABLE: "No Data Available",
  FILTER_TITLE:"Filter",
  CLEAR_ALL: 'Clear All',
  APPLY_BUTTON: "Apply",
  DATE:"date",
  DUE_DATE_ERROR: "From date should always greater than to date",
  SEARCH1: "search1",
    TRANSPARENT: 'transparent',
    SEARCH_PAYOUT:"Search Payout",
    START_DATE:"Start Date",  
    END_DATE:"End Date",
    SELECT_NAME: 'Select Name',
    PAYMENTS:"Payments",
    FEE:"Fee",
    CLOSE:"Close",
    CROSS:"close",
    FLAT_FEE:"Flat Fee",
    INFO:"info",
    SUCCESS_IMAGE:'../../assets/images/banklocal/success.png',
    COPY_CLICK_ERROR: 'FAILED TO COPY TEXT TO CLIPBOARD',
    BACK_TO_HOME:'Back to Home',
    WITHDRAW_AGAIN:'Send  again',
     BALANCE:"Balance :",
     SEARCH_COIN:"Search Coin",
     COIN: "Coin",
     CONTINUE:"Continue",
     SUMMERY:"Summery",
     THANL_YOU:'Thank you !',
     YOUR_TRANSACTION_OF:"Your Transaction of",
     CRYPTO:"Crypto",
     FIAT:"Fiat",
     PAYOUT_CRYPTO:"payoutcrypto",
     PAYOUT_FIAT:"payoutfiat",
     AVAILABLE_BALANCE:"Available Balance",
     MIN:"Min : ",
     MAX:"Max : ",
     IS_REQUIRED:"is required",
    VERIFICATION_REQUIRED :"Without verifications you can't withdraw. Please select send verifications from",
    SECURITY_SECTION:"security section",
    SECURITY:"Security",
    BANK_NAME:"Bank",
    ACCOUNT_NUMBER:"Account Number",
    SWIFT_CODE:"SwiftBicCode",
    WALLETS_ALL_ASSETS:"WalletsAllAssets",
  PAYOUT_TITLE: {
    PAY_OUT: "Pay Out",
    BTN_FIAT: "Fiat",
    BTN_CRYPTO: "Crypto",
    PAYMENTS:"payments",
    PAYOUT:"Pay-Out"
  },
  NAVIGATION: {
    PAY_OUT_LIST: "PayOutList",
   PAY_OUT:"Payout",
   TRANSACTIONS_DETAILS:"TransactionDetails",
   SUCCESS_PAGE:"SendPayoutSuccessPage",
   PAY_OUT_FORM:"PayOutForm",
   CRYPTO_PAYOUT:"CryptoPayout",
    CRYPTO_SEND:"CryptoSend",
    SUMMERY_DETAILS:"SummeryDetails",
    VAULTS_LIST:"VaultList",
    FIAT_PAYOUT:"FiatPayout",
    SEND_PAYEES: "Send",
    COMING_SOON:"ComingSoon"
  },
  FIELD_NAMES: {
    MERCHANT_ID: "merchantId",
    MERCHANT_NAME: "merchantName",
    CURRENCY: "currency",
    NETWORK: "networkName",
    AMOUNT: "amount",
    PAYEE: "payee",
    FIAT_CURRENCY: "fiatCurrency",
    CUSTOMER_WALLET_ID:"customerWalletId",
    FINAL_AMOUNT:"finalAmount"

  },
 SETFIELDS: {
    SET_ISlOADING: "setIsLoading",
    BUTTON_LOADER:"buttonLoader",
    SET_LOOKUPS: "setLookups",
    SET_ERRORS: "setErrors",
    SET_VALUES: "setValues",
    CURRENCY:"currency",
    NETWORK:"network",
    FIAT_CURRENCY:"fiatCoins",
    FIAT_CURRENCY_LOADER:"fiatCurrencyLoader",
    SUMMERY_LOADER:"summeryLoader",
  },
  LABLES: {
    VAULT: "Vault",
    COIN: "Coin",
    NETWORK: "Network",
    PAYEE: "Payee",
    FIAT_CURRENCY: "Select Currency",
    AMOUNT:"Amount",
    Net_AMOUNT:"Net Amount",

  },
  PLACEHOLDERS: {
    SELECT_VAULT: "Select Vault",
    SELECT_COIN: "Select Coin",
    SELECT_NETWORK: "Select Network",
    ENTER_AMOUNT: "Enter Amount",
    SELECT_PAYEE: "Select Payee",
    SELECT_FIAT_CURRENCY: "Select Fiat Currency",
    FIAT_CURRENCY: "Select Currency",
    ZERO:"0.00",
    SEARCH_AND_SELECT_PAYEE:"Search And Select Payee ",
    CALUCLATING_NET_AMOUNT:"calculating Net Amount",
  },
  MODEL_TITLES: {
    MERCHANT: "Merchant",
    CURRENCY: "Currency",
    NETWORK: "Network",
    PAYEE: "Payee",
    FIAT_CURRENCY: "Fiat Currency",
    PAY_OUT_CRYPTO:"Pay-Out crypto",
    PAY_OUT_FIAT:"Pay-Out Fiat",
  },
  SUMMERY_SCREEN:{
    CURRENCY:"Currency",
    NETWORK:"Network",
    PAYEE:"Payee",
    NAME:"Name",
    WALLET_ADDRESS:"Wallet Address",
    TOTAL_AMOUNT:"Total Amount",
    FEE:"Fee",
    FLAT_FEE:"Flat Fee",
    NET_AMOUNT:"Net Amount",
    DOCUMENT:"Document",
  },
  UPLOAD_DOC:{
    NO_DOCUMENT_SELECTED:'No document selected',
   FIAT_DOCUMENT :'fiatDocument',
   FILE_SIZE_SHOULD_2MB:'File size should be max 2MB',
   DOCUMENT:"document",
   DOC_TYPES:"Only .jpg, .jpeg, .png, .pdf, .xls, .xlsx files are allowed.",
   SUCCESS:'success',
   UPLOAD_YOUR_DOCUMENT:"Upload Your Document",
  }
};
