export const PROFILE_CONSTANTS = {
  UPLOAD_PROFILE: 'api/v1/uploadprofile',
  CUSTOMER_AVATAR: 'api/v1/Customer/Avatar',
  REFERRAL_DETAILS: (id: any) => `/api/v1/Security/getReferralDetails/customer/${id}`,
  SECURITY_VERIFICATIONS: '/api/v1/security/verifications',
  SECURITY_2FA: '/api/v1/security/2fa',
  SECURITY_SETTINGS: '/api/v1/security/settings',
  SECURITY_RESET_PWD: (customerId: any) => `/api/v1/Security/ResetPWD/${customerId}`,
  PROFILE_VIEW: (id: any) => `/api/v1/Common/ProfileView/${id}`,
  CUSTOMER_CHANGE_PWD: 'api/v1/Customer/ChangePWD',
  UPLOAD_FILE: 'api/v1/uploadfile',
  KYC_LOOKUP: 'api/v1/kyc/lookup',
  KYB_DOCUMENT_TYPES: 'api/v1/Common/KybDocumentTypesLu',
  KYC: 'api/v1/kyc',
  CUSTOMER_ADDRESS: 'api/v1/Customer/Address',
  KYC_DOCUMENTS: 'api/v1/kyc/documents',
  BYTES_TO_IMAGE: 'BytesToImageConveter',
  KYB: 'api/v1/kyb',
  KYB_COMPANY: 'api/v1/kyb/company',
  KYB_UBOS: 'api/v1/kyb/ubos',
  KYB_DIRECTORS: 'api/v1/kyb/directors',
  KYB_SHAREHOLDER: 'api/v1/kyb/shareholder',
  KYB_REPRESENTATIVE: 'api/v1/kyb/representative',
  KYC_DETAILS: 'api/v1/kyc/details',
  BANKS_KYC_REQUIREMENTS: (programId: string) => `api/v1/banks/${programId}/kycrequirements`,
  ADDRESSES: 'api/v1/addresses',
  KYC_STATE: 'api/v1/kyc/state',
  SETTINGS_2FA_GOOGLE: 'api/v1/settings/2fa/google/enable',
  KYC_KYB_STATE: (custamerId: any) => `api/v1/Common/M/KycState/${custamerId}`,
  SECURITY_PASSWORD_RESET: 'api/v1/security/password/reset',
  VERIFY_GOOGLE_AUTHENTICATOR: '/api/v1/VerifyGoogleAuthenticator',
  CUSTOMERS_ACCOUNT_CLOSE: '/api/v1/customers/accounts/close',
  FILE_PREVIEW: (id: any) => `api/v1/filePreview/${id}`,
  CASE_MESSAGE: (id: any) => `api/v1/case/${id}/message`,
  CASES_UPLOAD_FILE: 'api/v1/casesuploadfile',
  CASES_ALERTS: 'api/v1/cases/alerts',
  REWARDS_DASHBOARD: (id: any) => `loyalty/dashboard/${id}`,
  REWARDS_QUESTS: (id: any) => `loyalty/quests/${id}`,
  REWARDS_QUESTS_ACTION: (action: string, id: string) => `loyalty/quests/${action}/${id}`,
  REWARDS_MYSTERY_BOXES: (id: string) => `loyalty/mystery-boxes/${id}`,
  REWARDS_QUESTS_JOIN: (qyuestId: string, id: string) => `loyalty/quests/${qyuestId}/join/${id}`,
  REWARDS_MYSTERY_BOXES_OPEN: (qyuestId: string, id: string) => `loyalty/mystery-boxes/${qyuestId}/open/${id}`,
  REWARDS_RULES: (id: string) => `loyalty/reward-rules/${id}`,
  REWARDS_REDEMPTION_CONFIG: 'loyalty/redemption/config',
  REWARDS_MYSTERY_BOXES_OPEN_BASE: 'loyalty/mystery-boxes/open/',
  REWARDS_LEDGER: (Id: any, sorceType: any, page: any, pageSize: any) => `loyalty/ledger/${Id}?sourceType=${sorceType}&limit=${pageSize}&offset=${page}`,
  PUSH_TOKEN: 'api/v1/M/token',
  DELETE_TOKEN: 'api/v1/M/deletetoken',
  TOKEN: 'api/v1/Token',
  FORGOT_PASSWORD: 'api/v1/Forgotpassword',
  REGISTER: 'api/v1/Register',
  API_V1_SECURITY_PERMISIIONS: (id: string) => `api/v1/security/permissions/${id}`

};
