export const ACCOUNTDASH_CONSTANTS = {
    ACCOUNT_SELECT_COMPONENT: "AccountSelect",
    ALL_CARDS_COMPONENT: 'AllNewCards',
    No_DATA_AVAILABLE: "No Data Available",
    FEE_TAB: "feesTab",
    FEES: 'Fees',
    ARROW_RIGHT: "arrow-right",
    EXCHNAGE: "Exchange",
    BANK: "Bank",
    CARDS: "Cards",
    BANK_DEPOSIT_FIAT: "bankdepositfiat",
    BANK_WITHDRAW_FIAT: "bankwithdrawfiat",
    SELECT_BANK: "Select Bank",
    COUNTINUE: "Continue",
    RECIPIENT_DETAILS: "Recipient Details",
    TRANSFER_DETAILS: 'Transfer Details',
    BANK_ACCOUNT_CREATION: "bankaccountcreation",
    BANKS: "BANK",
    CREATE_ACCOUNT_FORM: "createAccountForm",
    PENDING:"pending",
    BANK_FEATURE_NAME:"banks",
    ACTION_NAME_DEPOSIT:"deposit",
    ACTION_NAME_WITHDRAW:"withdraw",
};

export const PAYMENT_LINK_CONSTENTS = {
    ADDS_AND_GRAPH_CONFIGUE: 'ADDS_AND_GRAPG_CONFIGURATION',
};

export const BANK_CONST = {
    EURO: "Euro",
    FAILED_TO_COPY_TEXT_TO_CLIPBOARD: "Failed to copy text to clipboard:",
    SHARING_BENEFICIARY: "Sharing Beneficiary:",
    ACCOUNT: "Banks",
    BANK_NAME: "Bank Name",
    FOR_DOMESTIC_TRANSFERS_ONLY: "For domestic transfers only",
    BENEFICIARY: "Beneficiary Name",
    YOUR_MONEY_IS_HELD_AND_PROTECTED_BY_LICENSED_BANK: "Your money is held and protected by licensed bank.",
    TRANSFERS_USUALLY_TAKE_A_FEW_HOURS: "Transfers usually take a few hours",
    ONLY_FAST_NETWORK_TRANSFERS_SUPPORTED: "Only FAST network transfers supported",
    PER_TRANSACTION_LIMIT: "$ 20,000.00 per transaction limit",
    IN_APP_BANK_TOP_SUPPORTED_FOR_DBS_MORE: "In-app bank top Supported for DBS, more",
    BIC: "BIC",
    LEARN_MORE: "Your money is held and protected by licensed bank. ",
    EXCHANGE: "Exchange",
    STATEMENT: "Statement",
    BENEFICIARY_ADDRESS: "Beneficiary Address",
    BENEFICIARY_ACCOUNT_NUMBER: "Beneficiary Account Number / IBAN ",
    ROUTING_NUMBER: "Beneficiary Routing Number",
    COUSTOMER_ID: "Customer ID",
    BENEFICIARY_BANK_NAME: "Beneficiary Bank Name",
    BENEFICIARY_BANK_ADDRESS: "Beneficiary Bank Address",
    BENEFICIARY_BANK_REFERENCE_NO: "Beneficiary Bank Reference No",
    SAHRE_BENEFICIARY: "Beneficiary Name:",
    SHARE_BENEFICIARY_ADDRESS: "Beneficiary Address:",
    SHARE_BENEFICIARY_ACCOUNT_NUMBER: "Beneficiary Account Number / IBAN:",
    SHARE_ROUTING_NUMBER: "Beneficiary Routing Number:",
    SHARE_COUSTOMER_ID: "Customer ID:",
    SHARE_BENEFICIARY_BANK_NAME: "Beneficiary Bank Name:",
    SHARE_BENEFICIARY_BANK_ADDRESS: "Beneficiary Bank Address:",
    SHARE_BENEFICIARY_BANK_REFERENCE_NO: "Beneficiary Bank Reference No:",
    IBAN_ACCOUNT_NUMBER: "IBAN/Account Number",
    SWIFT_BIC_CODE: "Swift/BIC Code",
    AVAILABLE_BALANCE: "Available Balance",
    SWIFT_CODE: "Swift/BIC Code",
    TOTAL_BALANCE: "Total Balance",
    SHARE_IBAN_ACCOUNT_NUMBER: "IBAN/Account Number:",
    SHARE_AVAILABLE_BALANCE: "Available Balance:",
    SHARE_SWIFT_CODE: "Swift/BIC Code:",
    SHARE_TOTAL_BALANCE: "Total Balance:",
    SHARE_SWIFT_BIC_CODE: "Swift/BIC Code:",
    SHARE_BANK_NAME: "Bank Name:",
    BALANCE: "Available Balance",
    DEPOSITE: "Deposit",
    _BANK: "_bank",
    CURRENCY_POP: "Currencypop",
    DRAFT: "Draft",
    SUBMITTED: "Submitted",
    FEE_PAGE: "Feepage",
    ALL_ACCOUNTS: "AllAccounts",
    WITHDRAW: "Withdraw",
    CURRENT_VALUE: "Current value",
    CREATE_ACCOUNT: "Create \n Account",
    ACCOUNTS: "Accounts",
    ADD_ACCOUNTS: "Add Accounts",
    NO_DATA_AVAILABLE: "No data available",
    DASHBOARD: "Dashboard",
    BANK: "Bank",
    SEND_AMOUNTS: "SendAmount",
    SELECT_ACCOUNT: "Select Account",
    DEPOSITE_MESSAGE: "Please make sure you are using the correct protocol otherwise you are risking losing the funds.",
    IAM_USING: "I am using Digital Bank:",
    BASE_URL: "https://arthadevcore.artha.work",
    DEV_ARTHAPAY: "https://devarthapayments.artha.work/",
    ARTHAPAY: "https://arthapayments.artha.work/",
    HELLOW: "Hello,",
    IWOULD_LIKE_TO_SHARE: "I would like to share my",
    ADDRESS_FOR_RECEIVING: "address for receiving funds:",
    THANK_YOU: "Thank you.",
    PERSIONAL: 'Personal',
    BUSINESS: "business",
};