export const PROFILE_GENERAL_SERVICE_CONSTANTS = {
    API_V1_SECURITY_VERIFICATIONS: 'api/v1/security/verifications',
    API_V1_SECURITY_2FA: 'api/v1/security/2fa',
    API_V1_SECURITY_SETTINGS: 'api/v1/security/settings',
    API_V1_SECURITY_PASSWORD_RESET: 'api/v1/security/password/reset',
    API_V1_HELP_CENTER: 'api/v1/m/HelpCenter',
    API_V1_FEES: 'api/v1/fees',
    API_V1_UPGRADE_FEES_DETAILS: (id: any, module: any) => `api/v1/upgrade/fees/${id}/details?module=${module}`,
    API_V1_REWARDS_DASHBOARD: (id: any) => `loyalty/dashboard/${id}`,
    API_V1_REWARDS_QUESTS: (id: any) => `loyalty/quests/${id}`,
    API_V1_REWARDS_QUESTS_ACTION: (action: string, id: string) => `loyalty/quests/${action}/${id}`,
    API_V1_REWARDS_QUESTS_JOIN: (questId: string, id: string) => `loyalty/quests/${questId}/join/${id}`,
    API_V1_REWARDS_MYSTERY_BOXES: (id: string) => `loyalty/mystery-boxes/${id}`,
    API_V1_REWARDS_MYSTERY_BOXES_OPEN: (questId: string, id: string) => `loyalty/mystery-boxes/${questId}/open/${id}`,
    API_V1_REWARDS_MYSTERY_BOXES_OPEN_BASE: 'loyalty/mystery-boxes/open/',
    API_V1_REWARDS_RULES: (id: string) => `loyalty/reward-rules/${id}`,
    API_V1_REWARDS_REDEMPTION_CONFIG: 'loyalty/redemption/config',
    API_V1_REWARDS_LEDGER: (id: any, sourceType: any, page: any, pageSize: any) => `loyalty/ledger/${id}?sourceType=${sourceType}&limit=${pageSize}&offset=${page}`,
    API_V1_MEMBERSHIPS_UPGRADE: 'api/v1/memberships/upgrade',
    API_V1_MEMBERSHIPS_UPGRADE_VAULTS: 'api/v1/memberships/upgrade/vaults',
    API_V1_MEMBERSHIPS_UPGRADE_FEE: 'api/v1/memberships/upgrade/fee',
    API_V1_EXCHANGE_RATE: (fromCoin: any, toCoin: any, amount: any) => `api/v1/exchangeRate?fromAsset=${fromCoin}&toAsset=${toCoin}&amount=${amount}`,
    API_V1_MEMBERSHIPS_UPGRADE_PAYMENT: 'api/v1/memberships/upgrade/payment',
    API_V1_CUSTOMERS_ACCOUNT_CLOSE: '/api/v1/customers/accounts/close'
}
