export const AUTH0_SIGNIN_CONSTANTS_KEYS = {
  SCREEN_TITLE: "AUTH0_SIGNIN.SCREEN_TITLE",
  EMAIL_LABEL: "AUTH0_SIGNIN.EMAIL_LABEL",
  EMAIL_PLACEHOLDER: "AUTH0_SIGNIN.EMAIL_PLACEHOLDER",
  PASSWORD_LABEL: "AUTH0_SIGNIN.PASSWORD_LABEL",
  PASSWORD_PLACEHOLDER: "AUTH0_SIGNIN.PASSWORD_PLACEHOLDER",
  SIGNIN_BUTTON_TEXT: "AUTH0_SIGNIN.SIGNIN_BUTTON_TEXT",
  EMAIL_REQUIRED_ERROR: "VALIDATION.EMAIL_IS_REQUIRED",
  INVALID_EMAIL_ERROR: "VALIDATION.INVALID_EMAIL_FORMAT",
  PASSWORD_REQUIRED_ERROR: "VALIDATION.PASSWORD_IS_REQUIRED",
  PASSWORD_MIN_LENGTH_ERROR: "VALIDATION.PASSWORD_MIN_LENGTH", // Example: "Password must be at least {minLength} characters"
  SIGNIN_FAILED_ERROR: "AUTH0_SIGNIN.SIGNIN_FAILED_ERROR",
};
