export const REFERRAL_CONST = {
    FAILED_TO_COPY: 'Failed to copy text to clipboard:',
    HELLO_I_WOULD_LIKE_TO_INVITE: "Hello, I would like to invite you to join Arthapayments.Use my referral code to sign up: ",
    IAM_USING_ARTHAPAYMENTS: "I am using Arthapayments: ",
    REFERRALS: "My Referrals",
    INVITE_FRIENDS: "Invite friends",
    SHARE_YOUR_REFERRAL_LINK: "Share Your Referral Link With \nFriends.Get Rewarded As Soon As They Complete Their Top-Up Task.",
    INVITE_FRIENDS_AND_GET_CRYPTO: "Invite friends and get Crypto",
    NO_DATA_AVAILABLE: "No data available",
    REFERRAL_DETAILS: "MemberDetails",
    FILTERS: "Filters",
    REF_ID: "Ref ID: ",
    REG_DATE: "Reg Date: ",
    REFERRAL_BONUS: "Referral Bonus",
    END_DATE_MUST_BE_LATER_THAN: "End date must be later than the start date.",
    BASE_URL: "https://devarthapayapi.artha.work/",
    DEV_ARTHAPAY: "https://devarthapayments.artha.work/",
    ARTHAPAY: "https://arthapayments.artha.work/",
}