export const WALLETS_ENDPOINTS = {
  CREATE_MERCHANT: 'api/v1/vault',
  KYC_ADDRESSES: 'api/v1/addresses',
  KYC_REQUIREMENTS: (id: string) => `/api/v1/payouts/${id}/kycrequirements`,
  SAVE_KYC_DETAILS: 'api/v1/payouts/kycrequirements',
  WALLETS_AMOUNT: (packageId: string) => `/api/v1/Merchant//availablebalance/BTC/${packageId}`,
  COUPON_BALANCE: '/api/v1/Affiliate/couponbalance',
  WALLET_KPIS: '/api/v1/Affiliate/customerwalletskpi',
  BONUS_KPIS: 'api/v1/Affiliate/m/bonuskpi',
  REFFERAL_KPIS: 'api/v1/Affiliate/m/referralKpi',
  WITHDRAW_KPIS: 'api/v1/Affiliate/m/withdrawamountkpi',
  BONUS_LEVELS: 'api/v1/Affiliate/m/ReferralBonusData',
  CASHWALLET_BALANCE: (customerId: string) => `api/v1/Affiliate/CashWallet/${customerId}`,
  SHOW_VAULTS: 'api/v1/vaults/crypto',
  FIAT_VAULTS_LIST: 'api/v1/Wallets/fiat',
  FIAT_DEPOSIT_DETAILS: (currency: string) => `api/v1/wallets/${currency}/fiat/deposit`,
  WITHDRAW_FIAT_FEE: 'api/v1/withdraw/fiat/fee',
  WITHDRAW_FIAT: 'api/v1/withdraw/fiat',
  WITHDRAW_FIAT_COIN_DETAILS: (selectedCoinId: string) => `api/v1/withdraw/wallets/${selectedCoinId}/fiat`,
  WITHDRAW_FIAT_PAYEES: (selectedCoin: string) => `api/v1/payees/fiat?currency=${selectedCoin}&feature=`,
  FIAT_COIN_DETAILS: (id: string) => `api/v1/wallets/${id}/details`,
  FIAT_COINS_LIST: (action: string) => `api/v1/Wallets/${action}/fiat`,
  SHOW_ASSETS: 'api/v1/vaults/crypto',
  WALLET_RECEIVED: (coinCode: string, actiontype: string) => `/api/v1/Vaults/wallets/${coinCode}/crypto/${actiontype}`,
  WITHDRAW_CRYPTO: 'api/v1/withdraw/crypto',
  WITHDRAW_CRYPTO_FEE: 'api/v1/withdraw/crypto/fee',
  CRYPTO_PAYEES: (network: string) => `api/v1/payees/crypto?netWork=${network}&search=null`,
  SPENDING_CHART: (days: number | string) => `api/v1/summary/transactions?days=${days}`,
};
