
export const PAYMENT_LINK_CONSTENTS = {
    CREATE_INVOICE: "Create Invoice",
    CREATE_STATIC: "Create Static",
    PAYMENT_LINK: "Payment Link",
    CREATE_PAYMENT_BUTTON: "Generate Static Payment Link",
    UPDATE_PAYMENT_BUTTON: "Update Static Payment Link",
    CONTINNUE: "Continue",
    FAILED_TO_COPY_TEXT_TO_CLIPBOARD: "Failed to copy text to clipboard:",
    I_WOULD_LIKE_TO_SHARE_MY_COIN: "Hello, I would like to share my coin:",
    ADDRESS_FOR_RECEIVING: "address for receiving",
    NOTE: " Note: Please make sure you are using the correct protocol otherwise you are risking losing the funds. I am using Digital Bank. Thank you.",
    FEE: "Fee",
    NETWORK: "Network",
    ORDERID: "OrderId",
    RECEPIENT: "Recepient's wallet address",
    RECEPIENT_NOTIFICATION: "When your payment status will change, we'll send to you notification",
    ADDRESS: "Address",
    SHARE: "Share",
    PAY_IN: "Pay-In",
    SEE_ALL: "See All",
    NO_DATA_AVAILABLE: "No data available",
    ACTIONS: "Actions",
    ALL_PAYMENT_LIST: "AllPaymentList",
    PAYEENT_DETAILS: "PaymentDetails",
    PAY_IN_DETAILS1: "Pay In Details",
    SETIS_LOADING: 'setIsLoading',
    INITIAL_LOADING: 'initialLoading',
    STATIC: 'Static',
    INVOICE: 'Invoice',
    INVOICE_TITLE: 'Invoice',
    SETVALUES: 'setValues',
    SET_ERRORS: 'setErrors',
    SET_DATA_LOADINGl: 'setDataLoading',
    BTN_LOADER: 'btnLoader',
    CREATE_INVOICE_COMPONENT: 'CreatePaymentInvoice',
    SUCCESS_MSG: 'Payment link created successfully!',
    NOT_PAID: 'not paid',
    PAYMENT_DETAILS_SCREEN: 'PaymentDetails',
    INVOICE_FROM_SUMMARY: "InvoiceSummary",
    STATIC_PAYMENT_LINK: "StaticPaymentView",
    TRANSPARENT: 'transparent',
    SEARCH_VAULT: 'Search Vault',
    SEARCH_COIN: 'Search Coin',
    ALL_VAULTS: "All Vaults",
    CREATE_PAYMENT: "CreateStaticPayment",
    PAID: "Paid",
    PARTIALLY_PAID: "Partially Paid",
    THIS_RECORD_HAS_ALREADY_BEEN_PAID: "This record has already been paid.",
    ADDRESS_LINE_CANNOT_CONTAIN_HTML_TAGS: 'Address Line cannot contain HTML tags.',
    ADDRESS_LINE_CONNOT_CONTAIN_EMOJIS: 'Address Line cannot contain emojis.',
    PAYMENTS: "Payments",
    PAYIN: "PayIn",
    TRANSACTIONS: "Transactions",
    TRANSACTIONS_SUMMARY: "Transactions Summary",
    ALL: "All",
    RECENT_TRANSACTIONS: "Recent Transactions",
    CARDS: "Cards",
    PAY_IN_DETAILS: "Pay-In Details",
    SHARE_PAYMENT_LINK: "Share Payment Link",
    CANCEL: "Cancel",
    SEARCH: "search",
    SEARCH1: "search1",
    DASHBOARD: "Dashboard",
    SEARCH_PAY_IN: "Search Pay-In",
    NULL: "null",
    AVAILABLE_BALANCE: "Available Balance",
    ADD_VAULT: "Add Vault",
    PAY_OUT: "Pay-Out",
    CREDIT_CARD: "credit-card",
    PAYEES: 'Payees',
    VAULTS: "Vaults",
    PORTFOLIO_STATUS: "Portfolio Status",
    SELECT_CURRENCY: "Select Currency",
    CREATE_NEW_VAULT: "Create New Vault",
    ALL_MERCHANT_ACCOUNTS: "AllMerchantAccounts",
    SAVE: "Save",
    BATCH_PAYMENTS: "BatchPayments",
    SEND_PAYMENTS: "SendPayments",
    PAYOUT_DASHOBORD: "payoutDashboard",
    PAYOUT_LIST: "PayOutList",
    PLEASE_ENTER_MERCHANT_NAME: "Please enter merchent name",
    GUID_FORMAT: "00000000-0000-0000-0000-000000000000",
    ACCOUNT: "Account",
    HARDWARE_BACK_PRESS: "hardwareBackPress",
    RECENT_INVOICES: "Recent Invoices",
    NUMARIC: 'numeric',
    CHECKBOX_OUTLINE: 'checkbox-outline',
    CHECKBOX: 'checkbox',
    IS_PAYCOMMISSION: 'isPayCommission',
    HARD_BACK_PRESS: 'hardwareBackPress',
    DASHBOARD_COMPONENT: 'Dashboard',
    SET_LOOKUPS: 'setLookups',
    INVOICE_FORM_ITEMDETAILS_COMPONENT: 'InvoiceFormItemDetails',
    DATE: 'date',
    ITEMDETAILS_COMPONENT: "ItemDetails",
    GUID_FORMATE: "00000000-0000-0000-0000-000000000000",
    PLUS: "plus",
    NEW: 'New',
    CREATE_PAYMENT_COMPONENT: 'CreateStaticPayment',
    COPY_CLICK_ERROR: 'FAILED TO COPY TEXT TO CLIPBOARD',
    SHARE_PAYMENT_LINK_TITLE: 'Share Payment Link',
    PAYIN_TITLE: 'Pay In',
    FILTER: 'filter',
    FILTER_TITLE: "Filter",
    APPLY_BUTTON: "Apply",
    CLEAR_ALL: 'Clear All',
    END_DATE: 'End Date',
    START_DATE: "Start Date",
    SELECT_NAME: 'Select Name',
    PAYMENT_LINK_HEADING: 'Payment Link',
    SEARCH_PAYMENT_LINK: 'Search Payment Link',
    CLOSE: 'Close',
    THE_FUNDS_PAID_BY_CLIENT_WILL: "The funds paid by your client will be sent to your business wallet",
    HELP_TO_UNDERSTAND_WHAT_IS_YOUR_CLIENT_PAYING: "Help to Understand what is your client paying for",
    PREVIEW: "Preview",
    IS_PREVIEW_MODAL_VISABLE: "isPreviewModalVisable",
    SET_PREVIEW_MODAL_VISABLE: "setPreviewModalVisable",
    SET_PREVIEW_TEMPLATE_MODEL: "setPreviewTemplateVisibile",
    SET_PREVIEW_TEMPLATE_DATA: "setPreviewTemplate",
    SET_PREVIEW_DATA: "setPreviewData",
    VALUET: "Vault",
    ORDER_ID: "Order ID",
    AMOUNT: "Amount",
    COIN: "Coin",
    PREVIEW_NETWORK: "Network",
    AMOUNT_TO_PAY: "Amount to pay",
    PAY_IN_GRID: "PayInGrid",
    STATIC_BUTTON_LOADER: "setIsBtnLoading",
    UPDATE_INVOICE: 'Update Invoice',
    EDIT_STATIC: 'Edit Static',
    UPDATE_STATIC_PAYMENT_LINK: 'Update Static Payment Link',
    UPDATE_INVOICE_PAYMENT_LINK: 'Update Invoice Payment Link',
    CLOSE_ANTDESIGN: "close",
    SECURITY: "Security",
    CUSTOMER_WALLET_ID: "customerWalletId",
    DUE_DATE_MUST_BE_GREATER_THAN_CURRENT_DATE: 'Due date must be greater than current date',
    VAULT_NOTE: "Note: Vault save process might take up to 2 minutes.",
    RECENT_PAYOUTS: "Recent Payouts",
    INVOICE_FORM: "InvoiceForm",
    AMOUNT_NOT_PAID: "Not Paid",
    PAY_OUT_CRYPTO: "payoutcrypto",
    ACTION_TYPE_PAYIN: "payin",
    CANCELLED: "Cancelled",
    PAYIN_HAS_BEEN_FULLY_PAID: "Pay-In has been fully paid.",
    CANNOT_STATE_CHANGE_CANCELLED_PAY_IN: "Cannot state change cancelled pay-In",
    CANNOT_EDIT_CANCELLED_PAYIN: "Cannot edit cancelled pay-In",
    PAY_IN_HAS_BEEN_PARTIALLY_PAID: "Pay-In has been partially paid.",
    PAYMENT_TYPE: "PaymentTypes",
    PAYMENTS_QUICK: "PAYMENTS",
    _PAYMENTS: "_payment",
    ADDS_AND_GRAPH_CONFIGUE: 'ADDS_AND_GRAPG_CONFIGURATION',
    ARE_YOU_WANT_TO_DELETE_THIS_ITEM: "Are you want to delete this item ?",
    NO: "No",
    YES: "Yes",
    VIEW_COMPONENT:"ViewComponent",
    EXPIRED_PAYIN:"Cannot edit Expired pay-In",
    PAYMENT_LINK_NAMES: {
        MERCHANT: "merchantId",
        MERCHANT_NAME: "merchantName",
        TYPE: 'invoiceType',
        ORDER_ID: "orderId",
        AMOUNT: "amount",
        COIN: "currency",
        NETWORK: "networkName",
        IS_PAYMENT_COMMISSION: "isPayCommission",
        INVOICE_NAME: "invoiceNumber",
        DATE_OF_BIRTH: "dateOfBirth",
        FROM_COMPANY: "companyName",
        CLIENT: "clientName",
        EMAIL: "emails",
        COUNTRY: "country",
        STATE: "state",
        CITY: "city",
        STREET_ADDRESS: "streetAddress",
        ZIP: 'zipCode',
        TAX_IDENTIFICATION_NUMBER: "taxIdentificationNumber",
        INVOICE_CURRENCY: "invoiceCurrency",
        DUE_DATE: "dueDate",
        PAYMENT_LINK:"PaymentLink"
    },
    PAYMENT_LINK_TITLES: {
        MERCHANT: "Marchant",
        VAULT: "Vault",
        TYPE: 'Type',
        ORDER_ID: "Order ID",
        AMOUNT: "Amount",
        DUE_DATE: "Due Date",
        COIN: "Select Coin",
        NETWORK: "Select Network",
        IS_PAYMENT_COMMISSION: "Client will pay commission",
        PAYMENT_TYPE: "Payment Type",
        TRANSACTION_DATE: "Transaction Date",
        WALLET_ADDRESS: "Wallet Address",
        STATUS: "Status",
        ENTER_AMOUNT_TITLE: "Enter amount to pay",
        CREATE_INVOICE_TITLE: "Create New Invoice",
        BASIC_INFO_TITLE: "Basic Information",
        INVOICE_NAME: "Invoice No",
        DATE_OF_BIRTH: "Date Of Birth ",
        FROM: "From",
        TO: "To",
        ITEM_DETAILS: "Item Details",
        FROM_COMPANY: "Company Name",
        CLIENT: "Client",
        EMAIL: "CC Emails",
        COUNTRY: "Country",
        STATE: "State",
        SELECT_COUNTRY: "Select Country",
        SELECT_STATE: "Select State",
        CITY: "City",
        STREET_ADDRESS: "Street",
        ZIP: 'Zip',
        TAX_IDENTIFICATION_NUMBER: "Tax Identifier number",
        INVOICE_CURRENCY: "Invoice Currency",
        INVOICE_TYPE: "Invoice Type"
    },
    PAYMENT_LINK_PLACEHOLDER: {
        MERCHANT: "Select Marchent",
        SELECT_VAULT: "Select Vault",
        TYPE: 'Select type',
        ORDER_ID: "Enter Order ID",
        AMOUNT: "Enter Amount",
        COIN: "Select coin",
        NETWORK: "Select network",
        SELECT_DUE_DATE: "Select Due Date",
        IS_PAYMENT_COMMISSION: "isPayCommission",
        SEARCH_TRANSACTIONS: "Search",
        NAME: "Enter Vault Name",
        INVOICE_NAME: "Invoice Name",
        DATE_OF_BIRTH: "Date Of Birth ",
        FROM_COMPANY: "Enter Company Name",
        CLIENT: "Enter Client Name",
        EMAIL: "CC Email",
        COUNTRY: "Country",
        STATE: "State",
        SELECT_COUNTRY: "Select Country",
        SELECT_STATE: "Select State",
        CITY: "Enter City",
        ENTER_CIRY: "Enter City",
        STREET_ADDRESS: "Enter Street Address",
        ZIP: 'Enter zip Code',
        TAX_IDENTIFICATION_NUMBER: "Enter Tax Identifier number",
        INVOICE_CURRENCY: "Select Currency",
        MERCHANT_NAME: 'merchantName',
        VAULT_NAME: 'Vault Name',
        ENTER_ITEM_NAME: 'Enter Item Name',
        ENTER_QUANTITY: 'Enter Quantity ',
        ENTER_UNIT_PRICE: 'Enter Unit Price ',
        CHOOSE_A_VAULT: "Choose a Vault",
        SELECT_ISSUED_DATE: "Select Issued Date",
        EXAMPLE_CCMAILS: "Example:john@gmail.com,james@gmail.com"
    },
    INVOICE_FORM_CONSTENTS: {
        INVOICE_DEATILS: "Invoice Details",
        ITEM_DETAILS: "Item Details",
        SUMMARY: 'Summary',
        DATE_FORMATE: "DD-MM-YYYY",
        ISSUE_DATE: 'issuedDate',
        DUE_DATE: 'dueDate',
        INVOICE_SUMMARY_COMPONENT: 'InvoiceSummary',
        CREATE_INVOICE: 'Create Invoice',
        AMOUNT_WITHOUT_TAX: "Total Amount (Excluding Tax):",
        TOTAL_DISCOUNT: 'Total Discount',
        TOTAL_TAX_AMOUNT: 'Total Tax Amount',
        QUANTITY: 'Quantity ',
        UNIT_PRICE: 'Unit Price ',
        DISCOUNT: 'Discount ',
        TAX: 'Tax ',
        DUE: "Due",
        SELECT_VAULT: 'Select Vault',
        CHOOSE_VAULT: "Choose Vault",
        SELECT_COIN: 'Select Coin',
        SELECT_NETWORK: 'Select Network',
        PAYMENT_NOTE: 'Payment Term Notes',
        PAYMENT_NOTE_PLACEHOLDER: "Enter Payment Terms / Notes",
        GENERATE_INVOICE: 'Generate Invoice',
        VAULT: 'merchantName',
        COIN: 'currency',
        NETWORK: 'networkName',
        NOTE: 'paymentNote',
        EDIT_ITEM_DETAILS_TITLE: "Edit Item Details",
        FIELD_NAME_ITEM_NAME: 'itemName',
        FIELD_NAME_QUANTITY: 'quantity',
        FIELD_NAME_UNIT_PRICE: 'unitPrice',
        FIELD_NAME_DISCOUNT: 'discountPercentage',
        FIELD_NAME_TAX: 'taxPercentage',
        FIELD_NAME_AMOUNT: 'amount',
        ITEM_NAME: 'Item Name',
        Amount: 'Amount',
        DUE_AMOUNT: 'Amount',
        AMOUNT_DUE: "Due Amount",
        OK: "Ok",
        CANCEL: 'Cancel',
        DUE_DATE_ERROR: "From date should always greater than to date",
        AT_LEAST_ONE_ITEM_IS_REQUIRED: "At least one item is required!",
        INVOICE_FORM_COMPONENT: 'InvoiceForm',
        ADD_ITEM_DETAILS: 'Add Item Details',
        DELETE: "delete",
        INVOICE_TYPE:"invoiceType",
    },
    WALLETS: {
        EUR: 'eur',
        USD: 'usd',
        CHF: 'chf',
        GBP: 'gbp'

    },
    STATIC_PAYMENT_LINK_CONSTANTS: {
        STATIC_PAYMENT_LINK: "Static Payment Link",
        SET_PAYMENT_LINK_DATA: "setPaymentLinkData",
        ORDER_ID: "Order ID",
        DUE_DATE: "Due Date",
        SET_STATIC_PAYMENT_LOADER: "setStaticPaymentLoader",
        CLOSE: "Close",
        SHARE_WITH_RECIPIENT: "Share with receipient",
        YOUR_PAY_NETWORK_FEE: "Your Pay Network fee",
        ADDRESS: "Address",
        RECIPIENT_WALLET_ADDRESS: "Recepient's wallet address",
        PAYMENT_LINK: "Payment Link",
        SHARE_ON_COIN: "Coin :",
        SHARE_ON_ADDRESS: "Address :",
        SHARE_ON_NETWORK: "NetWork :",
        SHARE_ON_PAYMENT_LINK: "Payment Link :",
        AN_ERROR_OCCURRED: "An error occurred",
        STATIC_PAYMENT_LINK_REDIRECT: "StaticPaymentView",
        STATIC_TEMPLATE_VIEW: "StaticView",
        HELLO_I_WOULD_LIKE_TO_SHARE_MY: "Hello, I would like to share my",
        ADDRESS_FOR_RECEIVING: "address for receiving:",
        PLEASE_MAKE_SURE_YOU_ARE_USING_THE_CORRECT_PROTOCAL: "Please make sure you are using the correct protocol otherwise you are risking losing the funds.",
PLEASE_DOUBLE_CHECK:"Note: Please double-check all details, including the selected coin and network, before Payment. Incorrect information may result in a loss of funds.",
        NOTE: "Note :",
        I_AM_USING: "I am using Payment Gateway: ",
        THANK_YOU: "Thank you.",
        ARTHA_TECHNOLOGIES: "Artha Technologies",
        TEMPLATE_LOADING: "templateLoading",
    },
    GENERATE_INVOICE_DATA: {
        ISSUED_DATE: "Issued Date",
        DUE_DATE: "Due Date",
        ADDRESS: "Address",
        TAX_IDENTIFICATION_NO: "Tax Identification No :",
        ITEM_NAME: "Item Name",
        QTY: "Qty",
        UNIT_PRICE: "Unit Price",
        Discount: "Discount(%)",
        DISCOUNT_PERCENTAGE: "Discount(%)",
        TAX_PERCENTAGE: "Tax (%)",
        AMOUNT: "Amount",
        AMOUNT_WITHOUT_TAX: "Amount without tax",
        TOTAL_DISCOUNT: "Discount",
        TOTAL_TAX_AMOUNT: "Total Tax amount",
        DUE: "Due",
        INVOICE_CURRENCY: "Invoice Currency :",
        CC_EMAIL: "CC Email :",
        PAYMENT_TERMS_NOTES: "Payment Terms / Notes",
        PAYIN_GRID_REDIRECTION: "PayInGrid",
        FULLY_PAID: "Fully Paid",
        STATUS: "Status :",
        PAID: "Paid",
        BILLED_TO: "Billed to",
        FROM: "From",
        NAME: "name",
        QUANTITY: "quantity",
        UNITPRICE: "unitPrice",
        DISCOUNTPERCENTAGE: "discountPercentage",
        TAXPERCNETAGE: "taxpercentage",


    },
    PAYMENTS_SCHEMA: {
        DUE_DATAE_GREATER: 'Due date must be greater than issued date',
        MUST_BE_25_CHARACTERS: 'Must be 25 characters or less',
        MUST_BE_20_CHARACTERS: 'Must be 20 characters or less',
        MUST_BE_50_CHARACTERS: 'Must be 50 characters or less',
        MUST_BE_18_CHARACTERS: 'Must be 18 characters or less',
        MUST_BE_35_CHARACTERS: 'Must be 35 characters or less',
        IS_REQUIRED: 'is required',
        ISSUED_DATE: 'issuedDate',
        MUST_BE_VALUE_10000000: 'Must be a valid number not exceeding 10,000,000',
        MUST_BE_VALUE_100: 'Must be a valid number not exceeding 100',
        GUID_FORMATE: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
    },
    PAYMENTS_KPI: {
        TOTAL_INVOICE: "Total Invoices",
        APPROVED: "Approved",
        AWAITING_PAYMENTS: "Awaiting Payment",
        PAY_IN_AMOUNTS: "Pay-In Balance",
        PAY_OUT_AMOUNTS: "Pay-Out Balance",
        FILE_INVOICE_ICON: "file-invoice-dollar",
        APPROVED_ICON: "check",
        AWAITING_PAYMENT_ICON: "table-clock",
        PAY_IN_AMOUNT_ICON: "wallet-travel",
        PAY_OUT_AMOUNT_ICON: "wallet-travel",
    },
    STATE_CHANGE: {
        CANCEL: "Cancel",
        SAVE: "Save",
        SELECT_STATUS: "Select Status",
        STATUS: "status",
        LABEL_SATUS: "Status",
        STATE: "State",
        CHANGE_STATUS: "Change Status",
        PAYIN: "payIn",
        IS_REQUIRED: 'is required',
        CLOSE: "close",

    }



}

export interface Currency {
    balance: number,
    code: string,
    coin: string,
    logo: string,
}
export interface TypePeriod {
    code: string,
    name: string,
    recorder: number
}
export interface GraphData {
    labels: string[],
    values1: number[],
    values2: number[]
}
export interface GenerateInvoiceInterafe {
    invoiceGetData: any,
    errorMsg: any,
    invoiceLoader: boolean,

}
export const DASHBOARD_SECTION_TYPES = {
    HEADER_BALANCES: 'HEADER_BALANCES',
    QUICK_LINKS: 'QUICK_LINKS',
    KPIS: 'KPIS',
    VAULTS: 'VAULTS',
    RECENT_PAYMENT_LINKS: 'RECENT_PAYMENT_LINKS',
    RECENT_PAYOUTS: 'RECENT_PAYOUTS',
    GRAPH: 'GRAPH',
    SPACER: 'SPACER', // For commonStyles.sectionGap
    SMALL_SPACER: 'SMALL_SPACER' // For commonStyles.mb20/mb24
};

export const SEND_CONST = {
    ADD_CONTACT: "Add Address",
    FAVORITE_NAME: "Favorite Name",
    ADDRESS: "Wallet Address",
    NETWORK: "Network",
    SELECT_THE_NETWORK: "Select the network",
    SLECET_ASSET_TO_SEND: "Select Asset to Withdraw",
    SEARCH: "Search Coin",
    SEND: "Withdraw",
    NEW: "New",
    RECENT: "Recent",
    SUCCESS: "Success!",
    AMOUNT_SEND_SUCCESSFULLY: "Your Transaction of",
    COMPLETED: "is Successfully Completed",
    SEND_CRYPTO: "Withdraw Crypto",
    YOU_HAVE: "You have",
    SENDING_TO: "Sending To",
    IN_YOUR_BALANCE: "in your account",
    PLACEHOLDER: "placeholder",
    PLEASE_ENTER_THE_AMOUNT: "Please enter valid amount.",
    INSUFICIENT_FUND: "Insuficient funds",
    TO: "Withdraw Amount",
    SUBHEAD: "subhead",
    CONST_AMOUNT: "0.00",
    CONTINUE: "Continue",
    SEND_AGAIN: "Send again",
    BACK_TO_HOME: "Back to Crypto",
    ORDER_PREVIEW: "Order Preview",
    AMOUNT: "Amount",
    INPUT_SCAN_ADDRESS: "Input Or Scan Address",
    PLEASE_ENTER_RECIPIENT_ADDRESS: "Please enter recipient's address.",
    ADD_PAYEE: "Add Payee",
    SEND_AMOUNTS: "SendAmounts",
    CRYPTO_WITHDRAW: "CryptoWithdraw",
    DASHBOARD: "Dashboard",
    SEARCH_ICON: "search1",
    SELECT_COIN: "Select Coin",
    ADD_CRYPTO_ADDRESS: 'Add Crypto',
    EDIT_CRYPTO_ADDRESS: 'Edit Crypto',
    CANCEL: 'Cancel',
    PAYMENTLINK: "paymentLink",
    PAYMENTS: "Payments",
    CRYPTO: "Crypto",
    CRYPTO_COIN_BALANCE: 'CryptoCoinBalance',
    SEND_CRYPTO_PREVIEW: "sendCryptoPreview",
    SUMMERY_DETAILS: "SummeryDetails",
    SEND_WALLE_PREVIEW: "SendWalletPreview",
    WITHDRAW: "Withdraw",
    RECENT_ADDRESSES: "Recent Addresses",
    NO_DATA_AVAILABLE: "No Data Available",
    ADD_CRYPTO_PAYEE: "addCryptoPayee",
    PLEASE_ENTER_AMOUNT: "Please Enter Amount.",
    AMOUNT_MUST_BE_GREATER_THAN_ZERO: " Amount must be greater than zero.",
    PLEASE_ENTER_VALID_AMOUNT: "Please enter valid amount.",
    YOU_HAVE_ENTERD_AN_AMOUNT_BELOW: "You have entered an amount below the minimum withdrawal. The minimum amount is",
    YOU_HAVE_ENTERD_AN_AMOUNT_ABOVE: "You have entered an amount above the maximum withdrawal. The maximum amount is",

    INSUFFIECIENT_BALANCE: "Insufficient Balance .",
    WALLET_SEND: "Walletsend",
    CRYPTO_SEND: "CryptoSend",
    SELECT_NETWORK_LABEL: "Select Network",
    I_WANT_TO_WITHDRAW: 'I Want to Withdraw ',
    SELECT_NETWORk: "Select Network",
    VAULT: "Vault",
    NUMERIC: "numeric" as const,
    AVAILABLE_BALANCE: "Available Balance : ",
    MIN: "Min - ",
    MAX: "Max - ",
    SELECT_ADDRESS: "Select Address",
    ADDRESSES: "Addresses",
    PLUSE: "plus",
    EYE: "eye",
    SELECT_NETWORKS: "Select Network",
    CLOSE: "close",
    TRANSAPARENT: "transparent",
    WITHDRAW_SUMMARY: "Withdraw Summary",
    ADD_CONTACT_COMPONENT: "AddContact",
    FEE: "Fee",
    FLAT_FEE: "Flat Fee",
    COIN: "Coin",
    SELF: "Self",
    THIRD_PARTY: "3rd Party",
    PLEASE_VERIFY_ADDRESS: "Please Verify address",
    ADDRESS_BOOK: "Addressbook",
    GRANTED: "granted",
    DENIED: "denied",
    ADDRESS_TYPE: "Address Type",
    TOCKEN: "Token",
    SELECT_TOCKEN: "Select Tocken",
    VERIFIED: "Verified",
    VERIFY: "Verify",
    CHECK_CIRCLE: "check-circle",
    SELECT_SOURCE: "Select Source",
    SAVE: "Save",
    SLIDE: "slide",
    ADD_VAULT: "Add Vault",
    PLUS: "plus",
    CRYPTO_EXCHANGE: "CryptoExchange",
    SELL_CRYPTO_EXCHNAGE: "SellCryptoExchange",
    WALLET_RECEIVE: "WalletReceive",
    HIDDEN: "hidden",
    APPROXIMATELY_EQUAL: "approximately-equal",
    CURRENT_VALUE: "Current value",
    BUY: 'Buy',
    SELL: "Sell",
    TRADE: 'Trade',
    DEPOSIT: 'Deposit',
    SELECT_PAYEE: "Select Payee",
    RECENT_PAYEE: "Recent Payees",
    SHOULD_NOT_EXCEED_NULL: "Should not exceed null"







}
export const CRYPTO_CONSTANTS = {
    CRYPTO_PORTFOLIO: "cryptoPortfolio",
    SEARCH_CURRENCY: "Search Currency",
    SEARCH_ICON: "search1",
    SEARCH_COIN: 'Search Coin',
    SELECT_CURRENCY: "Select Currency ",
    SELECT_COIN: "Select Coin",
    BEFORE_DISCOUNT_COMMISSION: 'Before Discount Commission',
    TIER_DISCOUNT: 'Tier Discount',
    CREDITS_USED: 'Digital Bank Credits Used',
    CHEVRON_DOWN: 'info',
    AMOUNT_MUST_BE_GEEATER_THAN_ZERO: "Amount must be greater than zero.",
    NO_DATA_AVAILABLE: "No Data Available",
    CRYPTO: "CRYPTO",
    DRAFT: "Draft",
    DEPOSIT_CRYPTO: "depositcrypto",
    CRYPTO_BALANCE: "CryptoBalance",
    SELECT_ASSET: "SelectAsset",
    SWAP_COINS_LIST: "SwapCoinsList",
    SECURITY: "Security",
    CRYPTO_PORTFOLIO_Comp: "CryptoPortfolio",
    BUY_CRYPTO_LIST: "BuyCryptoList",
    SELL_CRYPTO_LIST: "SellCryptoList",
    CRYPTO_COIN_RECEIVE: "CryptoCoinReceive",
    TOTAL_CRYPTO: 'Total Crypto',
    CURRENT_VALUE: "Current value",
    EXCHANGE: 'EXCHANGE',
    BUY: 'Buy',
    TRADE: 'Trade',
    ADD_VAULT: 'Add Vault',
    SELL: 'Sell',
    SWAP: 'Swap',
    WITHDRAW: 'Withdraw',
    DEPOSIT: 'Deposit',
    PORTFOLIO: 'Portfolio',
    SHOW_ASSETS: "Show By Asset",
    CHECK_BOX: 'checkbox',
    CHECK_BOX_OUTLINE: 'checkbox-outline',
    SEE_ALL: 'See All',
    PORTFOLIO_STATUS: "Transactions Summary",
    ACCOUNT_TYPE_CRYPTO: "Crypto",
    ADD_COUPON: "AddCoupon",
    WITHOUT_VERIFICATIONS_YOU_CANT_WITHDRAW_PLEASE_SELECT_SEND_VERIFICATIONS_FORM: 'Without verifications you cant withdraw. Please select send verifications from',
    SECURITY_SELECTION: "security section",
    FIAT_WITHDRAW: "FiatWithdraw",
    EXPAND_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/arthapay-mobile-images/expand_icon.svg",
    WITHDRAW_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/arthapay-mobile-images/payin_nav_icon.svg",
    ADD_VAULT_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/arthapay-mobile-images/crypto-addvault.svg",
    DEPOSIT_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/arthapay-mobile-images/payin_nav_icon.svg",
    TRADE_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/Trade.svg",
    ADDS_AND_GRAPH_CONFIGURATION: "ADDS_AND_GRAPG_CONFIGURATION",
    WALLETS: "WALLETS",
    VAULTS:"Vaults",
}

export const KYC_FORM_FIELDS = {
    FIRST_NAME: 'firstName',
    LAST_NAME: 'lastName',
    EMAIL: 'email',
    PHONE_CODE: 'phoneCode',
    PHONE_NUMBER: 'phoneNumber',
    BIRTH_DATE: 'birthDate',
    OCCUPATION: 'occupation',
    COUNTRY: 'country',
    ADDRESS: 'address',
    DOC_TYPE: 'docType',
    DOC_NUMBER: 'docNumber',
    EXPIRY_DATE: 'expiryDate',
    FRONT_ID: 'frontId',
    BACK_ID: 'backId'
}