export const SEND_CONST = {
    ADD_CONTACT: "Add Address",
    FAVORITE_NAME: "Favorite Name",
    ADDRESS: "Wallet Address",
    NETWORK: "Network",
    SELECT_THE_NETWORK: "Select the network",
    SLECET_ASSET_TO_SEND: "Select Asset to Withdraw",
    SEARCH: "Search Coin",
    SEND: "Withdraw",
    NEW: "New",
    RECENT: "Recent",
    SUCCESS: "Success!",
    AMOUNT_SEND_SUCCESSFULLY: "Your Transaction of",
    COMPLETED: "is Successfully Completed",
    SEND_CRYPTO: "Withdraw Crypto",
    YOU_HAVE: "You have",
    SENDING_TO: "Sending To",
    IN_YOUR_BALANCE: "in your account",
    PLACEHOLDER: "placeholder",
    PLEASE_ENTER_THE_AMOUNT: "Please enter valid amount.",
    INSUFICIENT_FUND: "Insuficient funds",
    TO: "Withdraw Amount",
    SUBHEAD: "subhead",
    CONST_AMOUNT: "0.00",
    CONTINUE: "Continue",
    SEND_AGAIN: "Send again",
    BACK_TO_HOME: "Back to Crypto",
    ORDER_PREVIEW: "Order Preview",
    AMOUNT: "Amount",
    INPUT_SCAN_ADDRESS: "Input Or Scan Address",
    PLEASE_ENTER_RECIPIENT_ADDRESS: "Please enter recipient's address.",
    ADD_PAYEE: "Add Payee",
    FIRST_PARTY:"1st Party",
    SEND_AMOUNTS: "SendAmounts",
    CRYPTO_WITHDRAW: "CryptoWithdraw",
    DASHBOARD: "Dashboard",
    SEARCH_ICON: "search1",
    SELECT_COIN: "Select Coin",
    ADD_CRYPTO_ADDRESS: 'Add Crypto ',
    EDIT_CRYPTO_ADDRESS: 'Edit Crypto',
    CANCEL: 'Cancel',
    PAYMENTLINK: "paymentLink",
    PAYMENTS: "Payments",
    CRYPTO: "Crypto",
    CRYPTO_COIN_BALANCE: 'CryptoCoinBalance',
    SEND_CRYPTO_PREVIEW: "sendCryptoPreview",
    SUMMERY_DETAILS: "SummeryDetails",
    SEND_WALLE_PREVIEW: "SendWalletPreview",
    WITHDRAW: "Withdraw",
    RECENT_ADDRESSES: "Recent Addresses",
    NO_DATA_AVAILABLE: "No Data Available",
    ADD_CRYPTO_PAYEE: "addCryptoPayee",
    PLEASE_ENTER_AMOUNT: "Please Enter Amount.",
    AMOUNT_MUST_BE_GREATER_THAN_ZERO: " Amount must be greater than zero.",
    PLEASE_ENTER_VALID_AMOUNT: "Please enter valid amount.",
    YOU_HAVE_ENTERD_AN_AMOUNT_BELOW: "You have entered an amount below the minimum withdrawal. The minimum amount is",
    INSUFFIECIENT_BALANCE: "Insufficient Balance .",
    WALLET_SEND: "Walletsend",
    CRYPTO_SEND: "CryptoSend",
    SELECT_NETWORK_LABEL: "Select Network",
    I_WANT_TO_WITHDRAW: 'I Want to Withdraw ',
    SELECT_NETWORk: "Select Network",
    VAULT: "Vault",
    NUMERIC: "numeric",
    AVAILABLE_BALANCE: "Available Balance : ",
    MIN: "Min - ",
    MAX: "Max - ",
    SELECT_ADDRESS: "Select Address",
    ADDRESSES: "Addresses",
    PLUSE: "plus",
    EYE: "eye",
    SELECT_NETWORKS: "Select Network",
    CLOSE: "close",
    TRANSAPARENT: "transparent",
    WITHDRAW_SUMMARY: "Withdraw Summary",
    ADD_CONTACT_COMPONENT: "AddContact",
    FEE: "Fee",
    FLAT_FEE: "Flat Fee",
    COIN: "Coin",
    SELF: "Self",
    THIRD_PARTY: "3rd Party",
    PLEASE_VERIFY_ADDRESS: "Please Verify address",
    ADDRESS_BOOK: "Addressbook",
    GRANTED: "granted",
    DENIED: "denied",
    ADDRESS_TYPE: "Address Type",
    TOCKEN: "Token",
    SELECT_TOCKEN: "Select Tocken",
    VERIFIED: "Verified",
    VERIFY: "Verify",
    CHECK_CIRCLE: "check-circle",
    SELECT_SOURCE: "Select Source",
    SAVE: "Save",
    SLIDE: "slide",
    ADD_VAULT: "Add Vault",
    PLUS: "plus",
    CRYPTO_EXCHANGE: "CryptoExchange",
    SELL_CRYPTO_EXCHNAGE: "SellCryptoExchange",
    WALLET_RECEIVE: "WalletReceive",
    HIDDEN: "hidden",
    APPROXIMATELY_EQUAL: "approximately-equal",
    CURRENT_VALUE: "Current value",
    BUY: 'Buy',
    SELL: "Sell",
    TRADE: 'Trade',
    DEPOSIT: 'Deposit',
    SELECT_PAYEE: "Select Payee",
    RECENT_PAYEE: "Recent Payees"







}
export const CRYPTO_CONSTANTS = {
    CRYPTO_PORTFOLIO: "cryptoPortfolio",
    SEARCH_CURRENCY: "Search Currency",
    SEARCH_ICON: "search1",
    SEARCH_COIN: 'Search Coin',
    SELECT_CURRENCY: "Select Currency ",
    SELECT_COIN: "Select Coin",
    BEFORE_DISCOUNT_COMMISSION: 'Before Discount Commission',
    TIER_DISCOUNT: 'Tier Discount',
    CREDITS_USED: 'Digital Bank Credits Used',
    CHEVRON_DOWN: 'info',
    AMOUNT_MUST_BE_GEEATER_THAN_ZERO: "Amount must be greater than zero.",
    NO_DATA_AVAILABLE: "No Data Available",
    CRYPTO: "CRYPTO",
    DRAFT: "Draft",
    DEPOSIT_CRYPTO: "depositcrypto",
    CRYPTO_BALANCE: "CryptoBalance",
    SELECT_ASSET: "SelectAsset",
    SWAP_COINS_LIST: "SwapCoinsList",
    SECURITY: "Security",
    CRYPTO_PORTFOLIO_Comp: "CryptoPortfolio",
    BUY_CRYPTO_LIST: "BuyCryptoList",
    SELL_CRYPTO_LIST: "SellCryptoList",
    CRYPTO_COIN_RECEIVE: "CryptoCoinReceive",
    TOTAL_CRYPTO: 'Total Crypto',
    CURRENT_VALUE: "Current value",
    EXCHANGE: 'EXCHANGE',
    BUY: 'Buy',
    TRADE: 'Trade',
    ADD_VAULT: 'Add Vault',
    SELL: 'Sell',
    SWAP: 'Swap',
    WITHDRAW: 'Withdraw',
    DEPOSIT: 'Deposit',
    PORTFOLIO: 'Portfolio',
    SHOW_ASSETS: "Show By Asset",
    CHECK_BOX: 'checkbox',
    CHECK_BOX_OUTLINE: 'checkbox-outline',
    SEE_ALL: 'See All',
    PORTFOLIO_STATUS: "Transactions Summary",
    ACCOUNT_TYPE_CRYPTO: "Crypto",
    ADD_COUPON:"AddCoupon",
    WITHOUT_VERIFICATIONS_YOU_CANT_WITHDRAW_PLEASE_SELECT_SEND_VERIFICATIONS_FORM: 'Without verifications you cant withdraw. Please select send verifications from',
    SECURITY_SELECTION: "security section",
    FIAT_WITHDRAW:"FiatWithdraw",
    EXPAND_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/arthapay-mobile-images/expand_icon.svg",
    WITHDRAW_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/arthapay-mobile-images/payin_nav_icon.svg",
    ADD_VAULT_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/arthapay-mobile-images/crypto-addvault.svg",
    DEPOSIT_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/arthapay-mobile-images/payin_nav_icon.svg",
    TRADE_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/Trade.svg",
    ADDS_AND_GRAPH_CONFIGURATION:"ADDS_AND_GRAPG_CONFIGURATION",
    WALLETS:"WALLETS"
}
export const SUCCESSPAGE_CONSTANTS = {
    CARDS_CYYPTO: 'cardsCrypto',
    CARDS_CYYPTO_COMPONENT: 'CardsCrypto',
    SELECT_ASSET: 'SelectAsset',
    DASHBOARD: "Dashboard",
    WITHDRAW_AGAIN: 'Withdraw  again',
    BACK_TO_CRYPTO: 'Back to Crypto'
};
export interface LoadingsState {
    portFolioDtaLoading: boolean;
    errorMessage:string;
    addModelVisible: boolean,
    kycModelVisible: boolean,
    graphDetailsLoading: boolean,
    totalBalLoading: boolean,
}

export const currencySymbols = {
    USDC: "$",
    USDT: "$",
    ETH: "Ξ",
    BTC: "₿",
};
