const PHILIPPINES_BANKS = [
  { id: 'BDO', name: 'BDO Unibank' },
  { id: 'BPI', name: 'Bank of the Philippine Islands' },
  { id: 'Metrobank', name: 'Metropolitan Bank & Trust Company' },
  { id: 'Landbank', name: 'Land Bank of the Philippines' },
  { id: 'PNB', name: 'Philippine National Bank' },
  { id: 'UnionBank', name: 'Union Bank of the Philippines' },
  { id: 'RCBC', name: 'Rizal Commercial Banking Corporation' },
  { id: 'Chinabank', name: 'China Banking Corporation' },
  { id: 'SecurityBank', name: 'Security Bank Corporation' },
  { id: 'EastWest', name: 'EastWest Banking Corporation' }
];

const MEXICO_BANKS = [
  { id: '002', name: 'Banamex', code: '002' },
  { id: '012', name: 'BBVA México', code: '012' },
  { id: '014', name: 'Santander', code: '014' },
  { id: '019', name: 'Banjercito', code: '019' },
  { id: '021', name: 'HSBC', code: '021' },
  { id: '030', name: 'Bajío', code: '030' },
  { id: '032', name: 'IXE', code: '032' },
  { id: '036', name: 'Inbursa', code: '036' },
  { id: '037', name: 'Interacciones', code: '037' },
  { id: '042', name: 'Mifel', code: '042' },
  { id: '044', name: 'Scotiabank', code: '044' },
  { id: '058', name: 'Banregio', code: '058' },
  { id: '059', name: 'Invex', code: '059' },
  { id: '060', name: 'Bansi', code: '060' },
  { id: '062', name: 'Afirme', code: '062' },
  { id: '072', name: 'Banorte', code: '072' },
  { id: '102', name: 'The Royal Bank', code: '102' },
  { id: '103', name: 'American Express', code: '103' },
  { id: '106', name: 'Bank of America', code: '106' },
  { id: '108', name: 'Bank of Tokyo', code: '108' },
  { id: '110', name: 'JP Morgan', code: '110' },
  { id: '112', name: 'Bmonex', code: '112' },
  { id: '113', name: 'Ve Por Mas', code: '113' },
  { id: '116', name: 'ING', code: '116' },
  { id: '124', name: 'Deutsche', code: '124' },
  { id: '126', name: 'Credit Suisse', code: '126' },
  { id: '127', name: 'Azteca', code: '127' },
  { id: '128', name: 'Autofin', code: '128' },
  { id: '129', name: 'Barclays', code: '129' },
  { id: '130', name: 'Compartamos', code: '130' },
  { id: '131', name: 'Banco Famsa', code: '131' },
  { id: '132', name: 'BMULTIVA', code: '132' },
  { id: '133', name: 'Actinver', code: '133' },
  { id: '134', name: 'Wal-Mart', code: '134' },
  { id: '135', name: 'Nafin', code: '135' },
  { id: '136', name: 'Interbanco', code: '136' },
  { id: '137', name: 'Bancoppel', code: '137' },
  { id: '138', name: 'ABC Capital', code: '138' },
  { id: '139', name: 'UBS Bank', code: '139' },
  { id: '140', name: 'Consubanco', code: '140' },
  { id: '141', name: 'Volkswagen', code: '141' },
  { id: '143', name: 'CIBanco', code: '143' },
  { id: '145', name: 'Bbase', code: '145' },
  { id: '147', name: 'Bankaool', code: '147' },
  { id: '148', name: 'PagaTodo', code: '148' },
  { id: '150', name: 'Inmobiliario', code: '150' },
  { id: '151', name: 'Donde', code: '151' },
  { id: '152', name: 'Bancrea', code: '152' },
  { id: '154', name: 'Banco Finterra', code: '154' },
  { id: '155', name: 'ICBC', code: '155' },
  { id: '156', name: 'Sabadell', code: '156' },
  { id: '157', name: 'Shinhan', code: '157' },
  { id: '158', name: 'Mizuho Bank', code: '158' },
  { id: '159', name: 'Bank of China', code: '159' },
  { id: '160', name: 'Banco S3', code: '160' },
  { id: '166', name: 'BanBajio', code: '166' },
  { id: '168', name: 'MUFG Bank', code: '168' },
  { id: '600', name: 'GBM', code: '600' },
  { id: '601', name: 'Monexcb', code: '601' },
  { id: '602', name: 'Masari', code: '602' },
  { id: '605', name: 'Value', code: '605' },
  { id: '606', name: 'CB Intercam', code: '606' },
  { id: '607', name: 'CI Bolsa', code: '607' },
  { id: '608', name: 'Vector', code: '608' },
  { id: '610', name: 'B&B', code: '610' },
  { id: '614', name: 'Accival', code: '614' },
  { id: '616', name: 'Finamex', code: '616' },
  { id: '617', name: 'Valmex', code: '617' },
  { id: '618', name: 'Unica', code: '618' },
  { id: '619', name: 'MAPFRE', code: '619' },
  { id: '620', name: 'Profuturo', code: '620' },
  { id: '621', name: 'CB Actinver', code: '621' },
  { id: '622', name: 'Oactin', code: '622' },
  { id: '623', name: 'Skandia', code: '623' },
  { id: '626', name: 'Cbdeutsche', code: '626' },
  { id: '627', name: 'Zurich', code: '627' },
  { id: '628', name: 'Zurichvi', code: '628' },
  { id: '629', name: 'Hipotecaria Su Casita', code: '629' },
  { id: '630', name: 'CB Ve Por Mas', code: '630' },
  { id: '631', name: 'Confia', code: '631' },
  { id: '632', name: 'Multiva Cbolsa', code: '632' },
  { id: '633', name: 'Principal', code: '633' },
  { id: '634', name: 'Fincomun', code: '634' },
  { id: '636', name: 'HDI Seguros', code: '636' },
  { id: '637', name: 'Order', code: '637' },
  { id: '638', name: 'Akala', code: '638' },
  { id: '640', name: 'JP Morgan CB', code: '640' },
  { id: '642', name: 'Reforma', code: '642' },
  { id: '646', name: 'STP', code: '646' },
  { id: '647', name: 'Telecomm', code: '647' },
  { id: '648', name: 'Evercore', code: '648' },
  { id: '649', name: 'Skandia', code: '649' },
  { id: '651', name: 'Segmty', code: '651' },
  { id: '652', name: 'Asea', code: '652' },
  { id: '653', name: 'Kuspit', code: '653' },
  { id: '655', name: 'Sofiexpress', code: '655' },
  { id: '656', name: 'Unagra', code: '656' },
  { id: '659', name: 'Opciones Empresariales Del Noreste', code: '659' },
  { id: '670', name: 'Libertad', code: '670' },
  { id: '901', name: 'CLS', code: '901' },
  { id: '902', name: 'INDEVAL', code: '902' },
  { id: '90601', name: 'Arcus', code: '90601' },
  { id: '90605', name: 'Fondo (Fira)', code: '90605' },
  { id: '90606', name: 'Invercap', code: '90606' },
  { id: '90608', name: 'Mufg', code: '90608' },
  { id: '90613', name: 'Operadora de Recursos Reforma', code: '90613' },
  { id: '90616', name: 'Unica', code: '90616' },
  { id: '90617', name: 'Fondo (Fira)', code: '90617' },
  { id: '90620', name: 'Profuturo', code: '90620' },
  { id: '90630', name: 'CB Intercam', code: '90630' },
  { id: '90631', name: 'Fincomun', code: '90631' },
  { id: '90634', name: 'Fincomun', code: '90634' },
  { id: '90636', name: 'Operadora de Recursos Reforma', code: '90636' },
  { id: '90638', name: 'Akala', code: '90638' },
  { id: '90642', name: 'Operadora de Recursos Reforma', code: '90642' },
  { id: '90646', name: 'Sistema de Transferencias y Pagos STP', code: '90646' },
  { id: '90648', name: 'Evercore', code: '90648' },
  { id: '90652', name: 'Asea', code: '90652' },
  { id: '90653', name: 'Kuspit', code: '90653' },
  { id: '90655', name: 'Sofiexpress', code: '90655' },
  { id: '90656', name: 'Unagra', code: '90656' },
  { id: '90659', name: 'Opciones Empresariales Del Noreste', code: '90659' },
  { id: '90670', name: 'Libertad Servicios Financieros', code: '90670' },
  { id: '90680', name: 'Cristobal Colon', code: '90680' },
  { id: '90683', name: 'Caja Pop Mexica', code: '90683' },
  { id: '90684', name: 'Transfer', code: '90684' },
  { id: '90685', name: 'Fondo (Fira)', code: '90685' },
  { id: '90686', name: 'Investa Bank', code: '90686' },
  { id: '90689', name: 'Fomped', code: '90689' },
  { id: '90901', name: 'CLS', code: '90901' },
  { id: '90902', name: 'Indeval', code: '90902' },
  { id: '90903', name: 'CoDi Valida', code: '90903' }
];

export const PAYMENT_METHODS_CONFIG = {
  'Bank Transfer': {
    type: 'bank_transfer',
    label: 'Bank Transfer',
    fields: [
      { name: 'accountNumber', label: 'GLOBAL_CONSTANTS.ACCOUNT_NUMBER', type: 'text', required: true, readonly: false },
      { name: 'accountHolderName', label: 'GLOBAL_CONSTANTS.ACCOUNT_HOLDER_NAME', type: 'text', required: true, readonly: false },
      { name: 'bankName', label: 'GLOBAL_CONSTANTS.BANK_NAME', type: 'text', required: true, readonly: false },
      { name: 'bankCode', label: 'GLOBAL_CONSTANTS.TARGET_BANK_CODE', type: 'text', required: false, readonly: false },
      { name: 'branchCode', label: 'GLOBAL_CONSTANTS.BRANCH_CODE', type: 'text', required: false, readonly: false },
      { name: 'swiftCode', label: 'GLOBAL_CONSTANTS.SWIFT_CODE', type: 'text', required: false, readonly: false }
    ]
  },
  PIXINFO: {
    type: 'pix',
    label: 'Brazil PIX',
    fields: [
      { name: 'pixKeyId', label: 'GLOBAL_CONSTANTS.PIX_KEY', type: 'text', required: true, readonly: false },
      { name: 'taxId', label: 'GLOBAL_CONSTANTS.TAX_ID_CPF_CNPJ', type: 'text', required: true, readonly: false }
    ]
  },
  INSTAPAYINFO: {
    type: 'instapay',
    label: 'Philippines InstaPay',
    fields: [
      { name: 'recipientName', label: 'GLOBAL_CONSTANTS.RECIPIENT_NAME', type: 'text', required: false, readonly: true },
      { name: 'recipientAddress', label: 'GLOBAL_CONSTANTS.RECIPIENT_ADDRESS', type: 'text', required: false, readonly: true },
      { name: 'recipientAccountNumber', label: 'GLOBAL_CONSTANTS.ACCOUNT_NUMBER', type: 'text', required: true, readonly: false },
      { name: 'channelSubject', label: 'GLOBAL_CONSTANTS.SELECT_BANK_PSP', type: 'dropdown', required: true, readonly: false, options: PHILIPPINES_BANKS },
      { name: 'remarks', label: 'GLOBAL_CONSTANTS.REMARKS', type: 'textarea', required: false, readonly: false }
    ]
  },
  SWIFTPAYPESONETINFO: {
    type: 'swiftpay_pesonet',
    label: 'PH PESONet',
    fields: [
      { name: 'recipientName', label: 'GLOBAL_CONSTANTS.RECIPIENT_NAME', type: 'text', required: false, readonly: true },
      { name: 'recipientAddress', label: 'GLOBAL_CONSTANTS.RECIPIENT_ADDRESS', type: 'text', required: false, readonly: true },
      { name: 'recipientAccountNumber', label: 'GLOBAL_CONSTANTS.ACCOUNT_NUMBER', type: 'text', required: true, readonly: false },
      { name: 'channelSubject', label: 'GLOBAL_CONSTANTS.SELECT_BANK_PSP', type: 'dropdown', required: true, readonly: false, options: PHILIPPINES_BANKS },
      { name: 'remarks', label: 'GLOBAL_CONSTANTS.REMARKS', type: 'textarea', required: false, readonly: false }
    ]
  },
  SPEIINFO: {
    type: 'spei',
    label: 'Mexico SPEI',
    fields: [
      { name: 'targetFirstName', label: 'GLOBAL_CONSTANTS.FIRST_NAME', type: 'text', required: false, readonly: true },
      { name: 'targetLastName', label: 'GLOBAL_CONSTANTS.LAST_NAME', type: 'text', required: false, readonly: true },
      { name: 'targetEmail', label: 'GLOBAL_CONSTANTS.E_MAIL', type: 'email', required: false, readonly: true },
      { name: 'targetIdentificationDocument', label: 'GLOBAL_CONSTANTS.DOCUMENT_NUMBER', type: 'text', required: false, readonly: true },
      { name: 'targetBankAccountId', label: 'GLOBAL_CONSTANTS.TARGET_CLABE_NUMBER', type: 'text', required: true, readonly: false },
      { name: 'targetBankName', label: 'GLOBAL_CONSTANTS.BANK_NAME', type: 'dropdown', required: true, readonly: false, options: MEXICO_BANKS },
      { name: 'targetBankCode', label: 'GLOBAL_CONSTANTS.TARGET_BANK_CODE', type: 'dropdown', required: true, readonly: false, searchPlaceholder: 'GLOBAL_CONSTANTS.SEARCH_BANK', options: MEXICO_BANKS },
      { name: 'targetBankBranchId', label: 'GLOBAL_CONSTANTS.BRANCH_ID', type: 'text', required: false, readonly: false },
      { name: 'targetBankId', label: 'GLOBAL_CONSTANTS.TARGET_BANK_ID', type: 'text', required: false, readonly: false }
    ]
  }
};

export const getPaymentMethodFields = (paymentMethod: string) => {
  return PAYMENT_METHODS_CONFIG[paymentMethod]?.fields || [];
};
