export const SET_SEND_EMAIL_ADDRESS = "SET_SEND_EMAIL_ADDRESS";
export const SET_SEND_PHONE_ADDRESS_ADDRESS = "SET_SEND_PHONE_ADDRESS_ADDRESS";
export const SET_SEND_BULLSWIPE_ID = "SET_SEND_BULLSWIPE_ID"
export const SET_SEND_PHONE_CODE_ADDRESS_ADDRESS = "SET_SEND_PHONE_CODE_ADDRESS_ADDRESS";
export const SET_FROM_RECEIVE="SET_FROM_RECEIVE";
export const SET_HIGHLIGHTED_WITHDRAW="SET_HIGHLIGHTED_WITHDRAW";
export const SET_MY_CARDS_INFO="SET_MY_CARDS_INFO";