
    export const CRYPTO_CONSTANTS = {
    CRYPTO_PORTFOLIO: "cryptoPortfolio",
    SEARCH_CURRENCY: "Search Currency",
    SEARCH_ICON: "search1",
    SEARCH_COIN: 'Search Coin',
    SELECT_CURRENCY: "Select Currency ",
    SELECT_COIN: "Select Coin",
    BEFORE_DISCOUNT_COMMISSION: 'Before Discount Commission',
    TIER_DISCOUNT: 'Tier Discount',
    CREDITS_USED: 'Digital Bank Credits Used',
    CHEVRON_DOWN: 'info',
    AMOUNT_MUST_BE_GEEATER_THAN_ZERO: "Amount must be greater than zero.",
    NO_DATA_AVAILABLE: "No Data Available",
    CRYPTO: "CRYPTO",
    DRAFT: "Draft",
    DEPOSIT_CRYPTO: "depositcrypto",
    CRYPTO_BALANCE: "CryptoBalance",
    SELECT_ASSET: "SelectAsset",
    SWAP_COINS_LIST: "SwapCoinsList",
    SECURITY: "Security",
    CRYPTO_PORTFOLIO_Comp: "CryptoPortfolio",
    BUY_CRYPTO_LIST: "BuyCryptoList",
    SELL_CRYPTO_LIST: "SellCryptoList",
    CRYPTO_COIN_RECEIVE: "CryptoCoinReceive",
    TOTAL_CRYPTO: 'Total Crypto',
    CURRENT_VALUE: "Current value",
    EXCHANGE: 'EXCHANGE',
    BUY: 'Buy',
    TRADE: 'Trade',
    ADD_VAULT: 'Add Vault',
    SELL: 'Sell',
    SWAP: 'Swap',
    WITHDRAW: 'Withdraw',
    DEPOSIT: 'Deposit',
    PORTFOLIO: 'Portfolio',
    SHOW_ASSETS: "Show By Asset",
    CHECK_BOX: 'checkbox',
    CHECK_BOX_OUTLINE: 'checkbox-outline',
    SEE_ALL: 'See All',
    PORTFOLIO_STATUS: "Transactions Summary",
    ACCOUNT_TYPE_CRYPTO: "Crypto",
    ADD_COUPON:"AddCoupon",
    WITHOUT_VERIFICATIONS_YOU_CANT_WITHDRAW_PLEASE_SELECT_SEND_VERIFICATIONS_FORM: 'Without verifications you cant withdraw. Please select send verifications from',
    SECURITY_SELECTION: "security section",
    FIAT_WITHDRAW:"FiatWithdraw",
    EXPAND_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/arthapay-mobile-images/expand_icon.svg",
    WITHDRAW_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/arthapay-mobile-images/payin_nav_icon.svg",
    ADD_VAULT_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/arthapay-mobile-images/crypto-addvault.svg",
    DEPOSIT_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/arthapay-mobile-images/payin_nav_icon.svg",
    TRADE_ICON: "https://devtstarthaone.blob.core.windows.net/arthaimages/Trade.svg",
    ADDS_AND_GRAPH_CONFIGURATION:"ADDS_AND_GRAPG_CONFIGURATION",
    WALLETS:"WALLETS",
    CURRENCY_ERROR_MSG:"No currency/network combinations found.",
    PAYOUT_CRYPTO:"payoutcrypto",
    DEFAULT:"Default",
    CRYPTO_DEPOSIT:"deposit",
    CRYPTO_WITHDRAW_CONSTANT:"Crypto Withdraw",
    CRYPTO_DEPOSIT_CONSTANT:"Crypto Deposit",
    CRYPTO_BALANCE_INFO:"Crypto balance",
    SUBMITTED:'"Submitted"',
    VAULTS:"Vaults",
    NO_NETWORK_DATA_FOUND_FOR:"No network data found for",
    DEPOSIT_METHOD_SELECT_NAVIGATION:"DepositMethodSelect",
    COMING_SOON_NAVOGATION:"ComingSoon",
    ERROR:'error',
    DEPOSIT_NETWORK_SELECT_NAVIGATION:"DepositSelectNetwork",
    DEPOSIT_VIEW_NAVIGATION:"DepositView",
    TRANSACRION_LIST_NAVIGATION:"TransactionList"
}