export const PAYMENTS_ENDPOINTS = {
  SUMMARY: (type: string | number) => `api/v1/payments/summary?type=${type}`,
  MERCHANTS: 'api/v1/payments/merchants',
  KPI: 'api/v1/payments/kpi',
  BALANCE_PAYIN: 'api/v1/payments/balance?type=payin',
  BALANCE_PAYOUT: 'api/v1/payments/balance?type=payout',
  PAYMENT_LINKS: (type: any, page: any, pageSize: any, search: any) => `api/v1/payments/${type}?page=${page}&pageSize=${pageSize}&search=${search}`,
  PAYOUT_LIST: (page: any, pageSize: any, search: any) => `/api/v1/payments/payout?page=${page}&pageSize=${pageSize}&search=${search}`,
  CURRENCIES: (id: any, type: string) => `api/v1/currencies/${id}?type=${type}`,
  FEATURE_STATUS: (type: any, status: any) => `api/v1/features/${type}/status/${status}/next`,
  INVOICE_DOWNLOAD: (txid: any, type: string) => `api/v1/invoices/${txid}/download?type=${type}`,
  PAYIN_STATE: (id: any) => `/api/v1/payments/payins/${id}/state`,
  PAYIN_INVOICE: 'api/v1/payments/payin/invoice',
  KYC_REQUIREMENTS_POST: 'api/v1/payouts/kycrequirements',
  MERCHANT_PREVIEW: (type: any) => `/api/v1/Merchant/${type}`,
  INVOICE_DETAILS: (id: any) => `api/v1/payins/invoice/${id}`,
  LOOKUP: 'api/v1/payments/lookup',
  FIAT_WALLETS_LOOKUP: 'api/v1/payments/fiatwallets/lookup',
  FIAT_DEPOSIT: (coin: string) => `api/v1/payments/${coin}/fiat/deposit`,
  PAYEES_FIAT: (toCurrency: any, feature: any) => `/api/v1/payees/fiat?currency=${toCurrency}&feature=${feature}`,
  PAYOUT_FIAT: (type: string) => `/api/v1/payments/payout/fiat?type=${type}`,
  PAYOUT_CRYPTO: (type: string) => `/api/v1/payments/payout/crypto?type=${type}`,
  PAYIN_FIAT_LIST: (page: any, pageSize: any) => `/api/v1/payments/payin/fiat?page=${page}&pageSize=${pageSize}&search=null`,
  PAYIN_FIAT_DETAILS: (coin: any) => `/api/v1/payments/payin/fiat/${coin}`,
  WALLETS_FIAT_PAYMENT_LINKS: (search: any) => `/api/v1/wallets/${search}/fiat/paymentlinks`,
  PAYOUT_MERCHANT: (type: any) => `api/v1/payouts/merchant?type=${type}`,
  PAYIN_DETAILS: (type: string, id: any) => `api/v1/payins/${type}/${id}`,
  PAYOUT_CRYPTO_FEE: '/api/v1/payout/crypto/fee',
  PAYOUT_FIAT_FEE: 'api/v1/payouts/fiat/fee',
  STATIC_INVOICE: 'api/v1/payments/payin/staticInvoice',
  STANDARD_INVOICE: 'api/v1/payments/payin/standardInvoice',
  PAYEES_FIAT_CURRENCY: (coin: any) => `/api/v1/payees/fiat?currency=${coin}`,
  KYC_KYB_DETAILS: '/api/v1/payments/kycKybdetails',
  FIAT_VIEW: (id: any) => `api/v1/m/payments/payin/fiat/${id}/view`,
  PAYOUT_CURRENCIES: (type: any) => `/api/v1/payouts/${type}/merchant`,
  PURPOSE: (id: any) => `/api/v1/purpose?id=${id}`,
  SOURCE_FUNDS: (id: any) => `/api/v1/sourceoffunds?id=${id}`,
  KYC_REQUIREMENTS: (id: any) => `/api/v1/payouts/${id}/kycrequirements`,
  ADDRESSES: 'api/v1/addresses',
  BENEFICIARIES: 'api/v1/beneficiaries?beneficiaryType=Ubo',
  UBO_DETAILS: (id: any) => `api/v1/uboDetails?id=${id}`,
  DYNAMIC_LOOKUP: (url: string) => `api/v1/${url}`,
  KYC_LOOKUP: 'api/v1/kyc/lookup',
  CUSTOMER_ADDRESS: '/api/v1/customer/address',
  FIAT_DETAILS: (currency: any, type: any) => `/api/v1/payments/payin/fiat/view?currency=${currency}&type=${type}`,
  FIAT_TRANSACTIONS: (type: any, currency: any, page: any, pageSize: any) => `/api/v1/payments/deposit/fiat/transactions?type=${type}&currency=${currency}&page=${page}&pageSize=${pageSize}`,
  EXCHANGE_CARDS_CRYPTO: '/api/v1/ExchangeWallet/Wallets/Crypto/Confirm',
  EXCHANGE_CRYPTO: '/api/v1/ExchangeWallet/Crypto/Confirm',
  CRYPTO_PAYEES: (customerId: any, walletCode: any) => `/api/v1/Common/PayeeCryptoLU/${customerId}/${walletCode}`,
};
