export const ADD_RECIPIENT = {
    EUR: "EUR",
    GBP: "GBP",
    CHF: "CHF",
    USD: "USD",
    JPY: "JPY",
    IS_REQUIRED: "Is required",
    PLEASE_ENTER_VALID_IBAN_NUMBER: "Please enter valid IBAN number",
    FULL_NAME_OF_THE_ACCOUNT_HOLDER: "Full Name Of The Account Holder",
    NAME_OF_THE_BUSINESS_ORGANISATION: "Name Of The Business/Organisation",
    IBAN: "IBAN",
    ROUTING_NUMBER: "Routing Number",
    ACCOUNT_NUMBER: "Account Number",
    SERVICE_PROVIDER: 'Servidce Provider ',
    UK_SORT_CODE: "UK Sort Code",
    VALIDATE: "Validate",
    VALIDATED: "Validated",
    CONFIRM: "Save",
    SWIFT_BIC_CODE: "Swift/BIC Code",
    IBAN_ACCOUNT_NUMBER: "Account number",
    COUNTRY: "Select Country",
    CITY: "City",
    POSTAL_CODE: "Pin Code",
    RECIPIENT_ADDRESS: "Recipient Address",
    ACH_ROUTING_NUMBER: "ACH Routing Number",
    NAME_OF_BUSSINESS_ORGANISATION: "Name Of Bussiness/Organisation",
    ACH: "ACH",
    RECIPIENT_EMAIL: "Recipient Email",
    SEPA_TRANSFER: "Sepa Transfer",
    BANK_DETAILS: "Bank Details",
    CURRENCY: "Currency",
    ENTER_THEIR_ORGANISATIONAL_ACCOUNT_DETAILS: "Enter Their Organisation’s Account Details",
    MY_SELF: "Personal",
    MG: "PS",
    A_BUSINESS_ORGANISATION: "Business",
    OTHERS: "Others",
    ADDRESSBOOK_RECIPIENT: "Recipient's Address",
    THEIR_EMAIL: "Their email",
    TO_SEND_EUR_DETAILS: `To send EUR to this account we need to use the SWIFT network. it’s slower so the transfer might take a day or two longer. also note that intermediary bank and your recipient’s bank might change extra fees to the amount received.`,
    ENTER_YOUR_ACCOUNT_DETAILS: "Enter your account details",
    PLEASE_ENTER_MORE_THAN_DIGIT: "Please enter more than 8 digit",
    ACH_NUMBER: "ACH Account Number",
    ADDRESS: 'Address',
    COUNTRY_NON: "Country",
    SLIDE: "slide",
    SELECT_MODULE: "Select Mudule",
    MODULE: "Module",
    FAVORITE_NAME: "Favorite Name",
    RECIPIENTS_DETAILS: "Recipient's Details",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    MIDLE_NAME: "Middle Name",
    DOB: "Date Of Birth",
    EMAIL: "Email",
    PHONE_NUMBER: "Phone Number",
    ADDITIONAL_INFO: "Additional Information",
    DOCUMENT_TYPE: "Document Type",
    FROND_SIDE: "Front Side ",
    BACK_SIDE: "Back Side",
    DOCUMENT_NUMBER: "Document Number",
    CLICK_TO_UPLOAD: "Click To Upload",
    PAYMENT_INFO: "Payment Information",
    PAYMENT_TYPE: "Payment Type ",
    SELECT_SERVICE_PROVIDER: 'Select Service Provider',
    PIX: "Pix",
    INSTAPAY: "Insta Pay",
    INSTA_PAY: "InstaPay",
    SWIFT_PAY: "SwiftPay Pesonet",
    SPEI: "SPEI",
    BANK_ACCOUNT: "Bank Account",
    PIX_KEY: "PIX Key ",
    TAX_ID: "Tax id ",
    RECIPIENT_MOBILE: "Recipient Mobile ",
    RECIPIENT_NAME: "Recipient Name ",
    RECIPIENT_LAST_NAME: "Recipient Last Name ",
    RECIPIENT_MIDLE_NAME: "Recipient Middle Name ",
    RECIPIENT_FIRST_NAME: "Recipient First Name ",
    RECIPIENT_REMARKS: "Remarks ",
    TARGET_NAME: "Target Name ",
    TARGET_LAST_NAME: "Target Last Name ",
    TARGET_EMAIL: "Target Email ",
    TARGET_DOCUMENT: "Target Document ",
    TARGET_BANK_NAME: "Bank Name ",
    TARGET_BANK_CODE: "Bank Code ",
    TARGET_BANK_BRANCH_ID: "Bank Branch ID ",
    TARGET_CLABE_NUMBER: "CLABE Number ",
    TARGET_BANK_ID: "Target Bank Id ",
    ACCOUNT_NAME: "Account Name ",
    ACCOUNT_TYPE: "Account Type ",
    BANK_DOC_NUMBER: "Bank Document Number ",
    ROUTING_NUMBER_IFSC_SORT: "Routing Number/Ifsc/Sort Code",
    BRANCH_ID: "Branch Id ",
    BANK_NAME: "Bank Name ",
    BANK_ADDRESS: "Bank Address ",
    BANK_COUNTRY: "Bank Country ",
    SWIFT_BTC: "Swift/BIC ",
    BRANCH_CODE: "Branch Code ",
    LOCAL_TRANSFER_CODE: "Local Transfer Code",
    NAME: 'name',
    STRING: 'string',
    NUMARIC: 'numeric',
    DOCUMENT: 'document',
    PHOTO: 'photo',
    ONLY_JPG_PNG: 'Accepts only jpg or png format ',
    FILE_SIZE: 'Image size should be less than 20MB',
    GUID: "00000000-0000-0000-0000-000000000000",
    PERSIONAL: 'Personal',
    PERSONAL: "personal",
    SUBMITED: "Submitted",
    ACTIVE: "Active",
    ADDRESS_BOOK_FIAT_LIST: "Addressbook",
    CLOUD_UPLOAD_OUTLINE: "cloud-upload-outline",
    CENETR: "center",
    LARGE: 'large',
    FULL_NAME: "Full Name",
    BUSINESS_TYPE: "Business Type",
    BUSINESS_REGISTRATION_NUMBER: "Business Registration Number",
    BUSINESS: "business",
    ADD_FIAT_ADDRESS: "Add Fiat",
    UPDATE_FIAT_ADDRESS: "Edit Fiat",
    BUSINES_FIAT_PAYEE: "BusinessFiatPayee",
    BASIC:"basic",
    FIAT_PAYEE_FIELD_PLACEHOLDERS: {
        FAVORITE_NAME: "Enter Favourite Name",
        COUNTRY: "Country",
        STATE: "state",
        CITY: "Enter City",
        POSTAL_CODE: "Enter Pin Code",
        ADDRESS: "Enter Address",
        FULL_NAME: "Enter Full Name",
        FIRST_NAME: "Enter First Name",
        MIDLE_NAME: "Enter Middle Name",
        LAST_NAME: "Enter Last Name",
        BIRTH_DAY_DATE: "birthDate",
        EMAIL: "Enter Email",
        PHONE_NUMBER: "Enter Phone Number",
        DOCUMENT_TYPE: "Select Document Type",
        WALLE_CODE: "Select Currency",
        DOCUMENT_NUMBER: "Enter Document Number",
        PAYMENT_TYPE: "Select Payment Type",
        RECIPIENT_AC_NUMBER: "Enter Account Number",
        SERVICE_PROVIDER: "serviceProvider",
        RECIPIENT_EMAIL: "recipientEmail",
        RECIPIENT_MOBILE: "recipientMobile",
        RECIPIENT_NAME: "recipientName",
        RECIPIENT_ADDRESS: "recipientAddress",
        RECIPIENT_LAST_NAME: "recipientLastName",
        RECIPIENT_MIDLE_NAME: "recipientMiddleName",
        RECIPIENT_FIRST_NAME: "recipientFirstName",
        REMARKS: "remarks",
        APP_NAME: "Select AppName",
        PIXED_KEY_ID: "pixKeyId",
        TAX_ID: "taxId",
        TARGET_NAME: "targetName",
        TARGET_LAST_NAME: "targetLastName",
        TARGET_EMAIL: "targetEmail",
        TARGET_DOCUMENT: "targetDocument",
        TAREGT_BANK_NAME: "targetBankName",
        TAREGT_BANK_CODE: "targetBankCode",
        TARGET_BANK_BRANCH_ID: "targetBankBranchId",
        TARGET_BANK_AC_ID: "targetBankAccountId",
        TAGET_BANK_ID: "targetBankId",
        ACCOUNT_NAME: "accountName",
        ACCOUNT_NUMBER: "accountNumber",
        ACCOUNT_TYPE: "accountType",
        BANK_DOC_NUMBER: "bankDocumentNumber",
        BANK_TRANSFER_CODE: "bankTransferCode",
        BRANCH_ID: "branchId",
        BANK_NAME: "bankName",
        BANK_ADDRESS: "bankAddress",
        BANK_COUNTRY: "bankCountry",
        SWIFT_BTC: "swiftBIC",
        BRANCH_CODE: "branchCode",
        CURRENCY: "currency",
        LOCAL_TRANSFER_CODE: "localTransferCode",
        BUSINESS_TYPE: "Select Business Type",
        BUSINESS_REGISTRATION_NUMBER: "businessRegistrationNo",
    },
    FIAT_PAYEE_FIELD_NAMES: {
        FAVORITE_NAME: "favouriteName",
        COUNTRY: "country",
        STREET: "street",
        STATE: "state",
        CITY: "city",
        POSTAL_CODE: "postalCode",
        ADDRESS: "address",
        FULL_NAME: "fullName",
        FIRST_NAME: "firstName",
        BUSINESS_NAME:"businessName",
        MIDLE_NAME: "middleName",
        LAST_NAME: "lastName",
        BIRTH_DAY_DATE: "birthDate",
        EMAIL: "email",
        PHONE_NUMBER: "phoneNumber",
        RELATION: "relation",
        DOCUMENT_TYPE: "documentType",
        WALLE_CODE: "currency",
        DOCUMENT_NUMBER: "documentNumber",
        PAYMENT_TYPE: "paymentType",
        DATE_OF_BIRTH: 'dob',
        RECIPIENT_AC_NUMBER: "recipientAccountNumber",
        SERVICE_PROVIDER: "serviceProvider",
        RECIPIENT_EMAIL: "recipientEmail",
        RECIPIENT_MOBILE: "recipientMobile",
        RECIPIENT_NAME: "recipientName",
        RECIPIENT_ADDRESS: "recipientAddress",
        RECIPIENT_LAST_NAME: "recipientLastName",
        RECIPIENT_MIDLE_NAME: "recipientMiddleName",
        RECIPIENT_FIRST_NAME: "recipientFirstName",
        REMARKS: "remarks",
        APP_NAME: "appName",
        PIXED_KEY_ID: "pixKeyId",
        TAX_ID: "taxId",
        TARGET_NAME: "targetName",
        TARGET_LAST_NAME: "targetLastName",
        TARGET_EMAIL: "targetEmail",
        TARGET_DOCUMENT: "targetDocument",
        TAREGT_BANK_NAME: "targetBankName",
        TAREGT_BANK_CODE: "targetBankCode",
        TARGET_BANK_BRANCH_ID: "targetBankBranchId",
        TARGET_BANK_AC_ID: "targetBankAccountId",
        TAGET_BANK_ID: "targetBankId",
        ACCOUNT_NAME: "accountName",
        ACCOUNT_NUMBER: "accountNumber",
        ACCOUNT_TYPE: "accountType",
        BANK_DOC_NUMBER: "bankDocumentNumber",
        BANK_TRANSFER_CODE: "bankTransferCode",
        BRANCH_ID: "branchId",
        BANK_NAME: "bankName",
        BANK_ADDRESS: "bankAddress",
        BANK_COUNTRY: "bankCountry",
        SWIFT_BTC: "swiftBIC",
        BRANCH_CODE: "branchCode",
        CURRENCY: "currency",
        LOCAL_TRANSFER_CODE: "localTransferCode",
        BUSINESS_TYPE: "businessType",
        BUSINESS_REGISTRATION_NUMBER: "businessRegistrationNo",
        UK_SHORT_CODE: "ukShortCode",
        I_BAN_NUMBER: "iBanNumber",
        PHONE_CODE: "phoneCode",
        BANK_COUNTRIE: "bankcountry",
        FRONT_ID_PHOTO: "frontIdPhoto",
        BACK_ID_PHOTO: "backIdPhoto",
        BACK_ID: "backId",
        FRONT_ID: "frontId",
        STABLE_COIN_PAYOUT: "stableCoinPayout",
    },
    APP_NAMES: {
        EXCHANGE_PAY: "Exchange",
        BANK: "Bank",
        PAYMENTS: "Payments"
    },
    VALIDATION_CONSTANTS: {
        FAVOURITE_NAME: 'Invalid favourite Name',
        CITY: 'Invalid city',
        POSTAL_CODE: 'Invalid postal code',
        ADDRESS: 'Invalid address',
        LAST_NAME: 'Invalid Last Name',
        FIRST_NAME: 'Invalid First Name',
        MIDLE_NAME: 'Invalid Middle Name',
        DOB_VALIDATION: 'Birth date must be greater than 18 years',
        EMAIL: 'Invalid Email',
        PH_NUMBER: 'Invalid Phone Number',
        ACCOUNT_NUMBER: 'Invalid Account Number',
        SHIFT_BIC_CODE: "Invalid Swift/ BIC/ Route Code",
        NAME: "Name",
        REMARKS: "Invalid Remarks",
        PIX_KEYID: "Invalid Pix KeyId",
        TAX_ID: "Invalid TaxId",
        CABLE_NUMBER: "Invalid Cable Number",
        BANK_NAME: "Invalid Bank Name",
        TARGET_DOCUMENT: "Invalid Target Document",
        BANK_CODE: "Invalid Bank Code",
        BANK_BRANCH_ID: "Invalid Target Bank BranchId",
        BANK_ID: "Invalid Bank Id",
        ACCOUNT_NAME: "Invalid Account Name",
        ACCOUNT_TYPE: "Invalid Account Type",
        PHONE_NUMBER: "phoneNumber",
        DOCUMENT_NUMBER: "Invalid Document Number",
        ROUTING_NUMBER: "Invalid Routing number",
        BRANCH_ID: "Invalid BranchId",
        BANK_ADDRESS: "Invalid Bank Address",
        SWIFT_BTC: "Invalid SwiftBIC",
        BRANCH_CODE: "Invalid Branch Code",
        CURRENCY: "Invalid Currency",
        LOCAL_TRANSFER_CODE: "Invalid Local TransferCode",

    },
    IMAGE_EXTENSION: {
        JPG: '.jpg',
        JPEG: '.jpeg',
        PNG: '.png'
    },

}
